"""Complete knowledge map — structured from Gemini research."""
from __future__ import annotations

from .types import KnowledgeTopic

# Sourced from: knowledge/The Complete Knowledge Map for Design Sense Intelligence.md

KNOWLEDGE_TOPICS: tuple[KnowledgeTopic, ...] = (
	KnowledgeTopic(
		'layout_systems', '1.1', 'Layout Systems', 'layout', 'layout_reviewer', 'subjective',
		'Structural frameworks organizing content across a 2D plane with predictable spatial relationships.',
		key_rules=(
			'Dominant interactive elements must occupy high-visibility zones.',
			'Layout structures must adapt gracefully across viewport dimensions.',
		),
		common_mistakes=('Rigid layouts that fracture with dynamic or localized content.',),
		evaluation_criteria='Can users predict where critical actions or data appear on a new page?',
		terminology=('fluid layouts', 'structural hierarchy', 'golden ratio'),
		keywords=('layout', 'page', 'structure'),
	),
	KnowledgeTopic(
		'grid_systems', '1.2', 'Grid Systems', 'layout', 'layout_reviewer', 'objective',
		'Subdivision of layout using columns and rows for modular alignment.',
		key_rules=(
			'Major UI elements must align to columns or baselines.',
			'Gutter widths must remain consistent across breakpoints.',
		),
		common_mistakes=('Breaking the grid off-axis without semantic intent.',),
		evaluation_criteria='Elements snap to column start/end points; grid reflows on smaller screens.',
		terminology=('columns', 'gutters', 'baseline grid', 'breakpoints'),
		keywords=('grid', 'column', 'gutter'),
	),
	KnowledgeTopic(
		'spacing_systems', '1.4', 'Spacing Systems and White Space', 'spacing', 'layout_reviewer', 'objective',
		'Mathematical scales for distance between and inside UI components.',
		key_rules=(
			'Use predictable base unit multipliers (8pt or 4pt grid).',
			'Distinguish macro-whitespace from micro-whitespace.',
		),
		common_mistakes=('Arbitrary spacing values like 13px next to 17px.',),
		evaluation_criteria='Spacing adheres to base multiplier; gaps reflect logical relationships.',
		terminology=('8pt grid', 'negative space', 'padding', 'margin'),
		keywords=('spacing', 'padding', 'margin', 'whitespace'),
	),
	KnowledgeTopic(
		'typography', '1.6', 'Typography', 'typography', 'typography_reviewer', 'objective',
		'Systematic arrangement of type for reading and hierarchy.',
		key_rules=(
			'Line height 130–150% of font size for body copy.',
			'Line length 60–75 characters maximum.',
			'All text must meet WCAG contrast ratios.',
		),
		common_mistakes=('Too many font families; insufficient contrast.',),
		evaluation_criteria='Type scale is mathematically sound; headings differentiate from body.',
		terminology=('leading', 'measure', 'typographic scale', 'x-height'),
		keywords=('typography', 'font', 'text', 'heading'),
	),
	KnowledgeTopic(
		'color_theory', '1.7', 'Color Theory', 'color', 'color_reviewer', 'objective',
		'Structured application of color for meaning, state, and brand.',
		key_rules=(
			'Color must never be the sole means of conveying information (WCAG 1.4.1).',
			'Deploy primary action color, neutral scale, and semantic scale.',
			'Avoid pure #000 on pure white for body text.',
		),
		common_mistakes=('Screaming UI with too many saturated colors.', 'Using accent color on non-interactive elements.'),
		evaluation_criteria='Interactive elements distinct from static text; contrast ≥ 4.5:1 for normal text.',
		terminology=('semantic color', 'OKLCH', 'hue', 'luminance'),
		keywords=('color', 'contrast', 'palette'),
	),
	KnowledgeTopic(
		'icons', '1.8', 'Icons', 'component', 'component_reviewer', 'subjective',
		'Symbolic illustrations representing concepts without relying entirely on text.',
		key_rules=(
			'Icons must be optically sized alongside text.',
			'Uniform stroke weights across the set.',
			'Avoid ambiguous icons without labels.',
		),
		common_mistakes=('Mystery meat navigation — icons without text labels.',),
		evaluation_criteria='Users can guess icon function; icons align to pixel grid.',
		terminology=('glyphs', 'SVG', 'stroke weight'),
		keywords=('icon', 'navigation'),
	),
	KnowledgeTopic(
		'design_tokens', '2.2', 'Design Tokens', 'tokens', 'color_reviewer', 'objective',
		'Platform-agnostic named entities for colors, typography, and spacing.',
		key_rules=(
			'Use global/primitive, alias/semantic, and component token tiers.',
			'Never use literal color names for semantic tiers (e.g. --blue vs --color-primary).',
			'Conform to W3C DTCG ($type, $value).',
		),
		common_mistakes=('Literal names on semantic tokens defeating theming.', 'Too many component tokens.'),
		evaluation_criteria='Token change propagates across connected components.',
		terminology=('W3C DTCG', 'primitive tokens', 'semantic aliases'),
		keywords=('token', 'theme', 'css variable'),
	),
	KnowledgeTopic(
		'design_patterns', '2.5', 'Design Patterns', 'ux', 'ux_reviewer', 'subjective',
		'Standardized solutions to common interface problems leveraging mental models.',
		key_rules=(
			'Do not reinvent standard patterns unless provably superior.',
			'Prefer conventions over configuration.',
		),
		common_mistakes=('Innovating on core navigation or checkout patterns.',),
		evaluation_criteria='First-time users complete the pattern without instructions.',
		terminology=('mental models', 'progressive disclosure', 'wizards'),
		keywords=('pattern', 'wizard', 'checkout', 'login'),
	),
	KnowledgeTopic(
		'interaction_design', '3.1', 'Interaction Design', 'ux', 'ux_reviewer', 'subjective',
		'Design of interactive behavior, flows, controls, and feedback.',
		key_rules=(
			'Interactive elements must visually suggest how they operate.',
			'Every user action must receive immediate system feedback.',
		),
		common_mistakes=('Flat designs where links and text are indistinguishable.',),
		evaluation_criteria='Measure interaction cost — actions and mental translations to goal.',
		terminology=('affordances', 'signifiers', 'feedback loops'),
		keywords=('interaction', 'click', 'button'),
	),
	KnowledgeTopic(
		'motion_design', '3.4', 'Motion Design', 'motion', 'motion_reviewer', 'subjective',
		'Choreographed animation communicating state changes and spatial relationships.',
		key_rules=(
			'Motion must be purposeful, not decorative.',
			'Transition durations typically 200–400ms.',
			'Use easing curves, not linear animation.',
		),
		common_mistakes=('Over-animating causing motion sickness or delay.',),
		evaluation_criteria='Animation explains hierarchy without drawing undue attention.',
		terminology=('easing', 'choreography', 'keyframes'),
		keywords=('animation', 'motion', 'transition'),
	),
	KnowledgeTopic(
		'ui_states', '3.5', 'UI States', 'ux', 'ux_reviewer', 'objective',
		'Temporal conditions: empty, loading, error, hover, focus, disabled.',
		key_rules=(
			'Empty states must orient user and provide CTA to populate.',
			'Prefer skeleton screens over infinite spinners.',
			'Errors in plain language with direct solution (WCAG 3.3.1).',
		),
		common_mistakes=('Dead-end empty states; blaming users in error copy.',),
		evaluation_criteria='Every component designed for hover, focus, active, disabled, error.',
		terminology=('skeleton screens', 'empty states', 'validation'),
		keywords=('loading', 'error', 'empty', 'state'),
	),
	KnowledgeTopic(
		'information_architecture', '4.1', 'Information Architecture', 'navigation', 'navigation_reviewer', 'subjective',
		'Structural design organizing and labeling content for findability.',
		key_rules=('Organizational structures align with user expectations, not org charts.',),
		common_mistakes=('Polysemous category labels causing cognitive paralysis.',),
		evaluation_criteria='Validate via tree testing without visual design cues.',
		terminology=('findability', 'depth', 'breadth', 'mental models'),
		keywords=('ia', 'structure', 'taxonomy'),
	),
	KnowledgeTopic(
		'navigation', '4.3', 'Navigation', 'navigation', 'navigation_reviewer', 'subjective',
		'Components and paradigms for moving through information architecture.',
		key_rules=(
			'Global navigation same location and sequence (WCAG 3.2.3).',
			'Breadcrumbs when hierarchy exceeds three levels.',
		),
		common_mistakes=('Hamburger menu on desktop hiding primary nav.',),
		evaluation_criteria='User on interior page knows location relative to site structure.',
		terminology=('breadcrumbs', 'mega-menus', 'wayfinding'),
		keywords=('nav', 'menu', 'breadcrumb'),
	),
	KnowledgeTopic(
		'user_flows', '4.4', 'User Flows', 'ux', 'ux_reviewer', 'subjective',
		'Mapped paths through an application to complete a task.',
		key_rules=(
			'Happy path requires minimum steps.',
			'Edge cases route user back to safety.',
		),
		common_mistakes=('Designing only happy path; ignoring errors and back navigation.',),
		evaluation_criteria='Measure interaction cost from entry to goal completion.',
		terminology=('happy path', 'edge cases', 'friction'),
		keywords=('flow', 'checkout', 'onboard', 'wizard'),
	),
	KnowledgeTopic(
		'forms', '5.1', 'Forms', 'ux', 'ux_reviewer', 'objective',
		'Interactive spaces for data submission and configuration.',
		key_rules=(
			'Labels always visible — placeholders are not labels.',
			'Input purposes programmatically determinable (WCAG 1.3.5).',
			'No validation before user finishes typing.',
		),
		common_mistakes=('Disabled submit without explaining missing data.',),
		evaluation_criteria='Errors adjacent to inputs; full keyboard navigation via Tab.',
		terminology=('inline validation', 'conversion bottleneck'),
		keywords=('form', 'input', 'validation', 'submit'),
	),
	KnowledgeTopic(
		'tables', '5.2', 'Tables', 'component', 'component_reviewer', 'objective',
		'Dense patterns for organizing large volumes of tabular data.',
		key_rules=(
			'Row identifiers human-readable.',
			'Numbers right-aligned for decimal scanning.',
			'Leftmost column sticky on mobile.',
		),
		common_mistakes=('Zebra striping without hover highlighting on wide monitors.',),
		evaluation_criteria='User traces row across viewport; sorting/filtering discoverable.',
		terminology=('sticky headers', 'inline editing', 'bulk actions'),
		keywords=('table', 'data grid', 'enterprise'),
	),
	KnowledgeTopic(
		'dashboards', '5.3', 'Dashboards', 'hierarchy', 'hierarchy_reviewer', 'subjective',
		'Dense interfaces aggregating KPIs and controls.',
		key_rules=(
			'Critical metrics in top-left quadrant (Western contexts).',
			'Drill-down into raw data underlying charts.',
		),
		common_mistakes=('Dumping every metric — chaotic wall of charts.',),
		evaluation_criteria='Deduce system health within 5 seconds of load.',
		terminology=('KPIs', 'widgets', 'progressive disclosure'),
		keywords=('dashboard', 'analytics', 'metrics'),
	),
	KnowledgeTopic(
		'landing_pages', '5.4', 'Landing Pages', 'layout', 'layout_reviewer', 'subjective',
		'Standalone pages with single conversion objective.',
		key_rules=(
			'Primary CTA visible above the fold.',
			'Remove distracting outbound navigation links.',
		),
		common_mistakes=('Buried value proposition; multiple competing CTAs (Hick\'s Law).',),
		evaluation_criteria='Measured via A/B testing conversion rates.',
		terminology=('CTA', 'CRO', 'above the fold'),
		keywords=('landing', 'marketing', 'homepage', 'conversion'),
	),
	KnowledgeTopic(
		'responsive_design', '6.1', 'Responsive Design', 'layout', 'layout_reviewer', 'objective',
		'Layouts scale and reflow across viewport sizes.',
		key_rules=(
			'Use relative units (%, em, rem) not absolute pixels.',
			'Mobile-first progressive enhancement.',
		),
		common_mistakes=('Desktop-first cramming onto mobile.',),
		evaluation_criteria='No overlapping content or horizontal scrolling (WCAG).',
		terminology=('breakpoints', 'media queries', 'fluid grids'),
		keywords=('responsive', 'mobile', 'viewport'),
	),
	KnowledgeTopic(
		'mobile_design', '6.2', 'Mobile Design', 'layout', 'layout_reviewer', 'objective',
		'Interfaces for handheld touch devices.',
		key_rules=(
			'Touch targets at least 44×44px (WCAG 2.5.8 minimum 24×24).',
			'Critical nav in thumb-reachable zones.',
		),
		common_mistakes=('Relying on hover states on touchscreens.',),
		evaluation_criteria='Primary task executable one-handed.',
		terminology=('thumb zones', 'gestures', 'bottom sheet'),
		keywords=('mobile', 'touch', 'thumb'),
	),
	KnowledgeTopic(
		'saas_design', '6.3', 'SaaS Design', 'ux', 'ux_reviewer', 'subjective',
		'Subscription software focused on retention and time-to-value.',
		key_rules=(
			'Empty states act as onboarding tutorials.',
			'Interface scales as user data grows over years.',
		),
		common_mistakes=('Pristine demo UI that breaks with real messy data.',),
		evaluation_criteria='Time-to-first-value and DAU retention metrics.',
		terminology=('onboarding', 'churn', 'time-to-value'),
		keywords=('saas', 'onboard', 'subscription'),
	),
	KnowledgeTopic(
		'enterprise_design', '6.4', 'Enterprise Design', 'component', 'component_reviewer', 'subjective',
		'Dense multi-functional software for expert mission-critical workflows.',
		key_rules=(
			'Support learning by doing with in-context cues.',
			'Preserve data density over consumer-style minimalism.',
		),
		common_mistakes=('Consumer-app white space hiding critical data.',),
		evaluation_criteria='Batch operations via keyboard without mouse.',
		terminology=('data density', 'integrative complexity'),
		keywords=('enterprise', 'admin', 'b2b', 'table'),
	),
	KnowledgeTopic(
		'ecommerce_design', '6.5', 'E-commerce Design', 'ux', 'ux_reviewer', 'subjective',
		'Storefronts and checkout optimized for conversion.',
		key_rules=(
			'Guest checkout without forced account creation.',
			'High-resolution product imagery with zoom.',
		),
		common_mistakes=('Multi-page checkout asking unnecessary information.',),
		evaluation_criteria='Cart abandonment and conversion rates.',
		terminology=('AOV', 'cart abandonment', 'trust signals'),
		keywords=('ecommerce', 'checkout', 'cart', 'shop'),
	),
	KnowledgeTopic(
		'cognitive_psychology', '7.1', 'Cognitive Psychology in UI', 'ux', 'ux_reviewer', 'subjective',
		'Application of memory, perception, and decision-making science to interfaces.',
		key_rules=(
			'Miller\'s Law: chunk information (7±2 items).',
			'Hick\'s Law: reduce choices per step.',
		),
		common_mistakes=('Instructions on screen A required on screen B.',),
		evaluation_criteria='Count cognitive decisions required to reach primary goal.',
		terminology=('cognitive load', 'chunking', 'working memory'),
		keywords=('cognitive', 'decision', 'choice'),
	),
	KnowledgeTopic(
		'visual_hierarchy', '7.2', 'Visual Hierarchy', 'hierarchy', 'hierarchy_reviewer', 'subjective',
		'Manipulation of size, weight, color, position to guide eye sequence.',
		key_rules=(
			'Most critical element carries heaviest visual weight.',
			'Related items grouped (Gestalt proximity).',
		),
		common_mistakes=('Everything large and bold — nothing stands out.',),
		evaluation_criteria='Squint test: primary focal point still distinct.',
		terminology=('F-Pattern', 'Z-Pattern', 'visual weight'),
		keywords=('hierarchy', 'focal', 'scan'),
	),
	KnowledgeTopic(
		'usability', '7.3', 'Usability', 'ux', 'ux_reviewer', 'subjective',
		'Ease, efficiency, and satisfaction achieving a specific goal.',
		key_rules=(
			'Users always in control with emergency exits (Undo/Cancel).',
			'Error prevention over good error messages.',
		),
		common_mistakes=('Aesthetic minimalism hiding critical navigation.',),
		evaluation_criteria='Heuristic evaluation or usability testing: task time and error rates.',
		terminology=('heuristics', 'learnability', 'efficiency'),
		keywords=('usability', 'heuristic'),
	),
	KnowledgeTopic(
		'wcag_accessibility', '8.1', 'WCAG 2.2 and Inclusive Design', 'accessibility', 'accessibility_reviewer', 'objective',
		'Ensuring interfaces are perceivable, operable, understandable, robust (POUR).',
		key_rules=(
			'Focus not obscured (2.4.11 AA).',
			'Drag alternatives required (2.5.7 AA).',
			'Target size minimum 24×24 CSS pixels (2.5.8 AA).',
			'Accessible authentication without cognitive tests (3.3.8 AA).',
		),
		common_mistakes=('Disabling zoom; keyboard traps in modals; color-only error states.',),
		evaluation_criteria='Screen reader announces state/role/value; full keyboard navigation.',
		terminology=('POUR', 'ARIA', 'focus indicators'),
		keywords=('wcag', 'a11y', 'accessibility'),
	),
)

TOPIC_BY_ID = {t.id: t for t in KNOWLEDGE_TOPICS}
