"""Generate ForOpenCode/kb/url_queue.yaml — curated high-signal URL list.

Run: python scripts/ux_kb/build_url_queue.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

OUT = Path(__file__).resolve().parents[2] / "ForOpenCode" / "kb" / "url_queue.yaml"


def U(
	id: str,
	url: str,
	topic: str,
	priority: str,
	get: str,
	skip: str,
	max_cards: int = 1,
	status: str = "queued",
	notes: str = "",
) -> dict:
	return {
		"id": id,
		"url": url,
		"topic": topic,
		"priority": priority,
		"get": get,
		"skip": skip,
		"max_cards": max_cards,
		"status": status,
		"notes": notes,
	}


# ---------------------------------------------------------------------------
# Curated corpus — Google AI UX Knowledge Engine report + RESOURCE_INDEX
# + selective public primaries for Frontend MCP competency questions.
# Prefer specific pages over hubs. Prefer Wayback for known 403 hosts.
# ---------------------------------------------------------------------------

URLS: list[dict] = []

# === A11Y ABSOLUTE (frozen topic — extract carefully; do not dilute) ===
URLS += [
	U("url_a11y_wcag22_target", "https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum", "a11y_absolute", "A",
	  "24x24 CSS px min; spacing exception circle; inline text exceptions",
	  "unrelated SC lists, marketing", 1, "queued",
	  "May 403 — use Wayback fallback url_a11y_wcag22_target_wayback; Absolute UX_A11Y_TARG_004"),
	U("url_a11y_wcag22_target_wayback", "https://web.archive.org/web/2024/https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum", "a11y_absolute", "A",
	  "Same as WCAG target size Understanding page via Wayback",
	  "archive chrome UI", 1, "queued", "Fallback if live W3C 403"),
	U("url_a11y_wcag22_overview", "https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/", "a11y_absolute", "A",
	  "New SC in 2.2 relevant to UI (focus, target, dragging)",
	  "full WCAG history essays", 1, "queued", "Absolute entry"),
	U("url_a11y_wcag22_contrast", "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum", "a11y_absolute", "A",
	  "4.5:1 text / 3:1 large; non-text contrast pointers",
	  "decorative exceptions fluff", 1, "queued", "Absolute UX_A11Y_CONT_005"),
	U("url_a11y_wcag22_focus_not_obscured", "https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum", "a11y_absolute", "A",
	  "Focused component not entirely hidden; sticky chrome implications",
	  "AAA variants unless needed", 1, "queued", "Absolute UX_A11Y_FOCUS_011"),
	U("url_a11y_webaim_checklist", "https://webaim.org/standards/wcag/checklist", "a11y_absolute", "A",
	  "Operational checklist mappings for contrast/target/keyboard",
	  "training course promos", 2, "queued", "Practitioner Absolute bridge"),
	U("url_a11y_webaim_contrast_checker", "https://webaim.org/resources/contrastchecker/", "a11y_absolute", "B",
	  "How contrast ratio is computed / AA AAA thresholds",
	  "tool chrome only", 1, "queued"),
	U("url_a11y_deque_target_size", "https://dequeuniversity.com/rules/axe/4.9/target-size", "a11y_absolute", "B",
	  "Automated detection rule for target size",
	  "axe product marketing", 1, "queued"),
	U("url_a11y_mdn_contrast", "https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast", "a11y_absolute", "B",
	  "MDN operational contrast guidance for web engineers",
	  "unrelated MDN nav", 1, "queued"),
	U("url_a11y_apg_keyboard", "https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/", "feedback_systems", "A",
	  "Keyboard interaction patterns; focus management expectations",
	  "full widget catalog", 2, "queued", "APG — keyboard / focus"),
]

# === MOTOR ERGONOMICS (Fitts, Steering) ===
URLS += [
	U("url_motor_fitts_yorku", "https://www.yorku.ca/mack/hhci2018.html", "motor_ergonomics", "A",
	  "Shannon ID=log2(A/W+1); MT; throughput by device",
	  "site chrome, unrelated HHCI chapters", 1, "done",
	  "Pilot processed; gold for Fitts"),
	U("url_motor_fitts_wiki_wayback", "https://web.archive.org/web/2024/https://en.wikipedia.org/wiki/Fitts%27s_law", "motor_ergonomics", "B",
	  "Shannon formulation summary; edge targets",
	  "archive chrome, talk page", 1, "queued", "Live Wikipedia often 403"),
	U("url_motor_fitts_csfieldguide", "https://www.csfieldguide.org.nz/en/chapters/human-computer-interaction/fitts-law/", "motor_ergonomics", "B",
	  "Teaching formulation + pointing examples",
	  "course nav", 1, "queued"),
	U("url_motor_steering_wayback", "https://web.archive.org/web/20240101000000/https://en.wikipedia.org/wiki/Steering_law", "motor_ergonomics", "A",
	  "T=a+b(A/W); cascading menus; Accot-Zhai",
	  "archive chrome", 1, "queued", "Pass1 Steering primary"),
	U("url_motor_steering_medium", "https://medium.com/beyonddesign/accot-zhai-steering-law-the-forgotten-law-in-hci-5beaa89c038b", "motor_ergonomics", "C",
	  "Menu tunnel engineering examples only",
	  "opinion fluff, author promo", 1, "queued", "Supporting only"),
	U("url_motor_lmu_fitts_steering_pdf", "https://www.medien.ifi.lmu.de/lehre/ss09/mmi1/20090507_FittsAndSteeringLaw.pdf", "motor_ergonomics", "B",
	  "Academic slides: Fitts + Steering formulas",
	  "course logistics", 1, "queued"),
	U("url_motor_lmu_hci_models_pdf", "https://www.medien.ifi.lmu.de/lehre/ss12/mmi1/vorlesung/MMI1-SS12-09-Basic-HCI-Models.pdf", "motor_ergonomics", "B",
	  "Basic HCI models overview including pointing",
	  "unrelated lecture admin", 1, "queued"),
]

# === COGNITIVE LOAD (Hick, Miller, Tesler, progressive disclosure) ===
URLS += [
	U("url_cog_hick_pmc", "https://pmc.ncbi.nlm.nih.gov/articles/PMC5998988/", "cognitive_load", "A",
	  "Hick-Hyman empirical mediation; choice entropy latency",
	  "methods appendices unless needed", 1, "queued", "UX_COG_HICK_002"),
	U("url_cog_hick_wiki_wayback", "https://web.archive.org/web/2024/https://en.wikipedia.org/wiki/Hick%27s_law", "cognitive_load", "B",
	  "Classic RT≈a+b log2(n) statement",
	  "archive chrome", 1, "queued"),
	U("url_cog_hick_decisionlab", "https://thedecisionlab.com/reference-guide/design/hicks-law", "cognitive_load", "B",
	  "Design implications of Hick; when NOT for experts",
	  "newsletter CTAs", 1, "queued"),
	U("url_cog_hick_research_collective", "https://research-collective.com/the-hick-hyman-law-in-design/", "cognitive_load", "B",
	  "Applied Hick-Hyman for UI choice sets",
	  "firm marketing", 1, "queued"),
	U("url_cog_tesler_medium", "https://medium.com/@shakindikithmini/teslers-law-in-ux-design-the-key-to-simplifying-complexity-6d54e3890792", "cognitive_load", "B",
	  "Conservation of complexity; push complexity into system",
	  "generic UX listicles", 1, "queued", "UX_ARC_TESL_007 seed"),
	U("url_cog_progressive_nng", "https://www.nngroup.com/articles/progressive-disclosure/", "cognitive_load", "A",
	  "Progressive disclosure definition; when advanced features hidden",
	  "related-article rails", 1, "queued", "CQ-SIT-04 / UX_ARC_PROG_003"),
	U("url_cog_progressive_enterprise", "https://medium.com/@theuxarchitect/progressive-disclosure-in-enterprise-design-less-is-more-until-it-isnt-01c8c6b57da9", "cognitive_load", "B",
	  "Enterprise exceptions when disclosure hurts experts",
	  "Medium paywall blur", 1, "queued"),
	U("url_cog_miller_nng", "https://www.nngroup.com/articles/miller-law/", "cognitive_load", "B",
	  "Chunking 7±2; working memory implications for menus",
	  "newsletter", 1, "queued", "Gap extrapolated Miller"),
	U("url_cog_aesthetic_nng", "https://www.nngroup.com/articles/aesthetic-usability-effect/", "aesthetic_usability", "A",
	  "Aesthetic-usability effect; masks usability problems",
	  "related rails", 1, "queued", "UX_COG_AEST_015"),
	U("url_cog_aesthetic_pixelmojo", "https://www.pixelmojo.io/blogs/the-aesthetic-usability-effect-why-good-looking-designs-feel-easier-to-use", "aesthetic_usability", "C",
	  "Secondary explanation only",
	  "agency promo", 1, "queued"),
]

# === ONBOARDING / BEHAVIOR (Fogg, activation) ===
URLS += [
	U("url_onb_fogg_official", "https://www.behaviormodel.org/", "onboarding", "A",
	  "B=MAP motivation ability prompt; diagnose missing element",
	  "workshop upsell", 2, "done", "Pilot + UX_COG_FOGG_013"),
	U("url_onb_fogg_logrocket", "https://blog.logrocket.com/ux-design/fogg-behavior-model/", "onboarding", "B",
	  "Product UX case applications of B=MAP",
	  "LogRocket product ads", 1, "queued"),
	U("url_onb_nng_onboarding", "https://www.nngroup.com/articles/mobile-website-onboarding/", "onboarding", "A",
	  "When onboarding helps vs skips; progressive vs tour",
	  "mobile-only caveats if desktop", 2, "queued", "CQ-PRD-02"),
	U("url_onb_nng_first_use", "https://www.nngroup.com/articles/first-time-ux/", "onboarding", "B",
	  "First-time UX patterns; reduce initial load",
	  "newsletter", 1, "queued"),
	U("url_onb_goal_gradient", "https://www.nngroup.com/articles/goal-gradient/", "onboarding", "B",
	  "Goal-gradient motivation near completion",
	  "unrelated articles", 1, "queued"),
]

# === FORMS / VALIDATION / FEEDBACK ===
URLS += [
	U("url_forms_baymard_form", "https://baymard.com/learn/form-design", "forms", "A",
	  "Single-column; label placement; field length; required marking",
	  "Baymard premium gates", 2, "queued", "UX_ARC_FORM_010"),
	U("url_forms_baymard_checkout", "https://baymard.com/learn/checkout-flow-ux-optimization", "checkout", "A",
	  "Checkout steps; guest; address; validation friction",
	  "premium paywall sections", 2, "queued", "UX_PRD_GUEST_001 related"),
	U("url_forms_baymard_payment", "https://baymard.com/learn/payment-ux", "checkout", "A",
	  "Payment UX standards; trust; field errors",
	  "premium", 1, "queued"),
	U("url_forms_cxl_validation", "https://cxl.com/blog/form-validation/", "forms", "A",
	  "Inline vs submit validation timing; messaging",
	  "CXL course CTAs", 1, "queued", "UX_INX_ERR_009"),
	U("url_forms_logrocket_validation", "https://blog.logrocket.com/ux-design/ux-form-validation-inline-after-submission/", "forms", "B",
	  "Inline vs after-submit tradeoffs",
	  "product ads", 1, "queued"),
	U("url_forms_ventureharbour", "https://ventureharbour.com/form-design-best-practices/", "forms", "B",
	  "Form layout practices; multi-step",
	  "long listicle filler", 1, "queued"),
	U("url_forms_freecodecamp_audit", "https://www.freecodecamp.org/news/automate-form-ux-audits-handbook/", "forms", "B",
	  "Detectable form UX audit criteria",
	  "tutorial tooling digressions", 1, "queued"),
	U("url_forms_nng_web_forms", "https://www.nngroup.com/articles/web-form-design/", "forms", "A",
	  "Classic web form guidelines",
	  "newsletter", 2, "queued"),
	U("url_forms_nng_errors", "https://www.nngroup.com/articles/error-message-guidelines/", "feedback_systems", "A",
	  "Error message guidelines; place near field; plain language",
	  "newsletter", 1, "queued", "UX_INX_ERR_009"),
	U("url_feedback_nng_response", "https://www.nngroup.com/articles/response-times-3-important-limits/", "feedback_systems", "A",
	  "0.1s / 1s / 10s response time limits",
	  "related rails", 1, "queued", "Self-descriptiveness timing"),
	U("url_feedback_nng_visibility", "https://www.nngroup.com/articles/visibility-system-status/", "feedback_systems", "A",
	  "Visibility of system status heuristic",
	  "newsletter", 1, "queued", "UX_INX_SELF_001"),
	U("url_feedback_nng_control", "https://www.nngroup.com/articles/user-control-and-freedom/", "feedback_systems", "A",
	  "Undo/cancel/exit; locus of control",
	  "newsletter", 1, "queued", "UX_INX_CTRL_001"),
]

# === CHECKOUT / CONVERSION / SEARCH (Baymard empirics) ===
URLS += [
	U("url_chk_baymard_search", "https://baymard.com/research/ecommerce-search", "checkout", "B",
	  "Search UX findings relevant to product findability",
	  "homepage hub fluff", 1, "queued"),
	U("url_chk_baymard_lists", "https://baymard.com/research/ecommerce-product-lists", "checkout", "B",
	  "Product list/filter UX empirics",
	  "premium lock", 1, "queued"),
	U("url_chk_baymard_homepage", "https://baymard.com/", "checkout", "C",
	  "Discover child research pages only — do not extract hub",
	  "entire marketing site", 0, "skipped", "Hub — discovery only"),
]

# === READING FLOW / VISUAL HIERARCHY / GESTALT ===
URLS += [
	U("url_vis_smashing_flow", "https://www.smashingmagazine.com/2015/04/design-principles-compositional-flow-and-rhythm/", "reading_flow", "A",
	  "F/Z/Gutenberg; CTA at end of flow",
	  "comments, author bio", 1, "done", "Pilot + UX_VIS_READ_014"),
	U("url_vis_nng_f_pattern", "https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/", "reading_flow", "A",
	  "F-pattern eyetracking implications for layout",
	  "newsletter", 1, "queued"),
	U("url_vis_nng_z_pattern", "https://www.nngroup.com/articles/zigzag-page-layout-pattern/", "reading_flow", "B",
	  "Z/zigzag layout for simpler pages",
	  "newsletter", 1, "queued"),
	U("url_vis_nng_proximity", "https://www.nngroup.com/articles/gestalt-proximity/", "hierarchy_density", "A",
	  "Proximity grouping; whitespace between vs within groups",
	  "related rails", 1, "done", "Pilot / UX_VIS_GEST_006"),
	U("url_vis_nng_proximity_principle", "https://www.nngroup.com/articles/proximity-principle-visual-perception/", "hierarchy_density", "A",
	  "Proximity principle visual perception (alt NN/g URL)",
	  "newsletter", 1, "queued"),
	U("url_vis_nng_similarity", "https://www.nngroup.com/articles/gestalt-similarity/", "hierarchy_density", "B",
	  "Similarity gestalt for controls grouping",
	  "newsletter", 1, "queued"),
	U("url_vis_nng_common_region", "https://www.nngroup.com/articles/common-region/", "hierarchy_density", "B",
	  "Common region / cards vs whitespace grouping",
	  "newsletter", 1, "queued"),
	U("url_vis_gestalt_openreplay", "https://blog.openreplay.com/gestalt-principles-for-web-design/", "hierarchy_density", "C",
	  "Secondary gestalt examples only",
	  "blog promo", 1, "queued", "Low credibility — supporting"),
	U("url_vis_gestalt_careerfoundry", "https://careerfoundry.com/en/blog/ui-design/what-are-gestalt-principles/", "hierarchy_density", "C",
	  "5 gestalt principles overview",
	  "bootcamp marketing", 1, "queued"),
	U("url_vis_nng_visual_hierarchy", "https://www.nngroup.com/articles/visual-hierarchy-ux-definition/", "hierarchy_density", "A",
	  "Visual hierarchy definition; detect equal-weight KPIs",
	  "newsletter", 1, "queued", "CQ-VIS-03"),
	U("url_vis_nng_dashboard", "https://www.nngroup.com/articles/dashboard-design/", "hierarchy_density", "A",
	  "Dashboard density vs scannability",
	  "newsletter", 2, "queued"),
]

# === ISO / SHNEIDERMAN / DIALOG PRINCIPLES ===
URLS += [
	U("url_iso_9241_110_explainer", "https://www.softwareevaluation.de/en/foundations/iso-9241-110-dialog-principles/", "feedback_systems", "A",
	  "ISO 9241-110 dialog principles list + engineering meaning",
	  "consultancy promo", 2, "queued", "UX_ARC_ISO_001"),
	U("url_iso_dialogdesign", "https://www.dialogdesign.dk/isos-dialogue-principles-2019/", "feedback_systems", "B",
	  "Dialogue principles 2020 commentary",
	  "firm marketing", 1, "queued"),
	U("url_iso_usability_de", "https://www.usability.de/en/usability-user-experience/glossary/interaction-principles.html", "feedback_systems", "B",
	  "Interaction principles glossary",
	  "agency nav", 1, "queued"),
	U("url_iso_wiki_wayback", "https://web.archive.org/web/2024/https://en.wikipedia.org/wiki/ISO_9241", "feedback_systems", "C",
	  "ISO 9241 family overview only",
	  "archive chrome", 1, "queued"),
	U("url_shneiderman_story", "https://thestory.is/en/journal/shneiderman-eight-golden-rules/", "feedback_systems", "A",
	  "8 golden rules; consistency feedback control errors",
	  "agency portfolio", 2, "queued"),
	U("url_shneiderman_wiki_wayback", "https://web.archive.org/web/2024/https://en.wikipedia.org/wiki/Ben_Shneiderman", "feedback_systems", "C",
	  "Bio pointer only — prefer thestory article",
	  "archive chrome", 1, "skipped", "Low utility alone"),
]

# === GOMS / KLM ===
URLS += [
	U("url_goms_wayback", "https://web.archive.org/web/20240101000000/https://en.wikipedia.org/wiki/GOMS", "motor_ergonomics", "A",
	  "GOMS/KLM operators; expert task time prediction",
	  "archive chrome", 1, "queued", "UX_HCI_KLM_008"),
	U("url_klm_wayback", "https://web.archive.org/web/2023/https://en.wikipedia.org/wiki/Keystroke-level_model", "motor_ergonomics", "A",
	  "KLM operators K M P H R; mental prep",
	  "archive chrome", 1, "queued"),
	U("url_goms_foundations_hci", "https://foundationsofhci.wordpress.com/module-5/", "motor_ergonomics", "B",
	  "Interface efficiency KLM GOMS teaching notes",
	  "wordpress chrome", 1, "queued"),
	U("url_goms_nau_pdf", "https://cefns.nau.edu/~edo/Classes/CS477_WWW/Docs/TechArticles/GOMS%20and%20Keystroke-Level%20Model.pdf", "motor_ergonomics", "B",
	  "GOMS and KLM technical article PDF",
	  "course wrappers", 1, "queued"),
]

# === HUMAN FACTORS / NASA-TLX ===
URLS += [
	U("url_hfe_nasa_tlx", "https://www.nasa.gov/human-systems-integration-division/nasa-task-load-index-tlx/", "human_factors", "A",
	  "Six subscales; weighted vs raw TLX",
	  "NASA site chrome", 1, "queued", "UX_HFE_TLX_001"),
	U("url_hfe_nasa_tlx_wayback", "https://web.archive.org/web/2024/https://en.wikipedia.org/wiki/NASA-TLX", "human_factors", "B",
	  "TLX subscales summary if NASA page thin",
	  "archive chrome", 1, "queued"),
	U("url_hfe_ahrq_tlx", "https://digital.ahrq.gov/health-it-tools-and-resources/evaluation-resources/workflow-assessment-health-it-toolkit/all-workflow-tools/nasa-task-load-index", "human_factors", "B",
	  "Healthcare workflow TLX usage notes",
	  "AHRQ nav", 1, "queued"),
	U("url_hfe_nng_perceived", "https://www.nngroup.com/articles/measuring-perceived-usability/", "human_factors", "B",
	  "SUS / NASA-TLX / SEQ after tasks",
	  "newsletter", 1, "queued"),
]

# === DESIGN SYSTEMS / TOKENS / DENSITY ===
URLS += [
	U("url_ds_carbon_home", "https://carbondesignsystem.com/", "design_tokens", "B",
	  "Find deep links only — prefer specific foundations pages",
	  "marketing homepage content", 0, "skipped", "Hub"),
	U("url_ds_carbon_a11y", "https://carbondesignsystem.com/guidelines/accessibility/overview/", "a11y_absolute", "A",
	  "Carbon a11y overview constraints for enterprise UI",
	  "component catalog dumps", 1, "queued"),
	U("url_ds_carbon_color", "https://carbondesignsystem.com/guidelines/color/overview/", "design_tokens", "A",
	  "Semantic color tokens; themes; contrast governance",
	  "palette swatches only without rules", 2, "queued", "UX_DS_TOKEN_001 support"),
	U("url_ds_carbon_spacing", "https://carbondesignsystem.com/guidelines/spacing/overview/", "hierarchy_density", "A",
	  "Spacing tokens; density implications",
	  "token tables without guidance", 1, "queued"),
	U("url_ds_carbon_type", "https://carbondesignsystem.com/guidelines/typography/overview/", "design_tokens", "B",
	  "Type tokens / hierarchy",
	  "font download promos", 1, "queued"),
	U("url_ds_carbon_2x", "https://carbondesignsystem.com/guidelines/2x-grid/overview/", "hierarchy_density", "B",
	  "2x grid / layout density",
	  "implementation SDK noise", 1, "queued"),
	U("url_ds_slds_tokens", "https://www.lightningdesignsystem.com/design-tokens/", "design_tokens", "A",
	  "SLDS design tokens; touch target notes if present",
	  "homepage fluff", 2, "queued", "May block — try tokens path"),
	U("url_ds_slds_guidelines", "https://www.lightningdesignsystem.com/guidelines/overview/", "hierarchy_density", "A",
	  "Enterprise density / clarity / efficiency guidelines",
	  "marketing", 2, "queued"),
	U("url_ds_slds_principles", "https://principles.design/examples/salesforce-lightning-design-principles", "hierarchy_density", "B",
	  "Lightning design principles summary",
	  "principles.design chrome", 1, "queued"),
	U("url_ds_polaris_colors", "https://polaris.shopify.com/design/colors", "design_tokens", "A",
	  "Semantic color roles critical/success; color has purpose",
	  "SPA shell fluff", 1, "queued", "Pass2"),
	U("url_ds_polaris_design", "https://polaris.shopify.com/design", "design_tokens", "B",
	  "Polaris design foundations overview",
	  "component index dumps", 1, "queued"),
	U("url_ds_polaris_principles", "https://principles.design/examples/shopify-principles", "design_tokens", "B",
	  "Shopify principles",
	  "site chrome", 1, "queued"),
	U("url_ds_atlassian_about", "https://atlassian.design/get-started/about-atlassian-design-system", "design_tokens", "B",
	  "ADS overview / building blocks",
	  "career pages", 1, "queued"),
	U("url_ds_atlassian_a11y", "https://atlassian.design/foundations/accessibility", "a11y_absolute", "A",
	  "Atlassian accessibility foundations",
	  "component gallery", 1, "queued"),
	U("url_ds_atlassian_tokens", "https://atlassian.design/tokens", "design_tokens", "A",
	  "Design tokens / theming for product UI",
	  "changelog noise", 2, "queued"),
	U("url_ds_atlassian_ai", "https://www.atlassian.com/blog/ai-at-work/atlassian-design-system-building-the-context-engine-for-the-ai-era", "agentic_ux", "B",
	  "AI + design tokens / context engine direction",
	  "corporate blog fluff", 1, "queued", "CQ-AI gap watch"),
	U("url_ds_material_color", "https://m3.material.io/styles/color/system/overview", "design_tokens", "B",
	  "Material 3 color roles (compare semantic role idea)",
	  "Android-only implementation", 1, "queued", "Cross-DS comparison only"),
	U("url_ds_radix_themes", "https://www.radix-ui.com/themes/docs/theme/color", "design_tokens", "C",
	  "Modern tokenized color scales examples",
	  "component API docs", 1, "queued"),
]

# === SETTINGS / IA / INFORMATION ARCHITECTURE ===
URLS += [
	U("url_set_nng_settings", "https://www.nngroup.com/articles/settings/", "settings", "A",
	  "Settings IA; findability; grouping preferences",
	  "newsletter", 2, "queued", "CQ-PRD-03"),
	U("url_set_nng_ia", "https://www.nngroup.com/articles/ia-vs-navigation/", "settings", "B",
	  "IA vs navigation distinction",
	  "newsletter", 1, "queued"),
	U("url_set_nng_categories", "https://www.nngroup.com/articles/categories-categories-categories/", "settings", "B",
	  "Category naming for dense products",
	  "newsletter", 1, "queued"),
	U("url_set_nng_mega_menus", "https://www.nngroup.com/articles/mega-menus-work-well/", "cognitive_load", "B",
	  "When mega-menus help vs Hick overload",
	  "newsletter", 1, "queued"),
]

# === AGENTIC / AI UX (gap — careful) ===
URLS += [
	U("url_ai_nng_genai", "https://www.nngroup.com/articles/ai-chatbots/", "agentic_ux", "B",
	  "Chatbot UX pitfalls; disclosure of control",
	  "newsletter", 1, "queued", "CQ-AI-02"),
	U("url_ai_nng_ai_ux", "https://www.nngroup.com/articles/ai-tools-user-experience/", "agentic_ux", "B",
	  "AI tool UX considerations",
	  "newsletter", 1, "queued"),
	U("url_ai_microsoft_guidelines", "https://www.microsoft.com/en-us/ai/responsible-ai", "agentic_ux", "C",
	  "Responsible AI high-level principles — not UI specifics",
	  "corporate hub", 1, "queued", "Watchlist — prefer UI-specific later"),
	U("url_ai_apple_hil", "https://developer.apple.com/design/human-interface-guidelines/machine-learning", "agentic_ux", "B",
	  "HIG machine learning: transparency, control, feedback",
	  "Apple platform-only chrome", 2, "queued"),
	U("url_ai_google_pair", "https://pair.withgoogle.com/guidebook", "agentic_ux", "A",
	  "People+AI Guidebook patterns for ML UX",
	  "case study fluff without rules", 2, "queued", "Strong agentic primary"),
]

# === LAWS OF UX AGGREGATORS (use sparingly — de-dupe later) ===
URLS += [
	U("url_agg_lawsofux", "https://lawsofux.com/", "general", "B",
	  "Index of named UX laws — discover deep-links only per law page",
	  "entire site dump as one extract", 0, "queued", "Hub — enqueue child pages as separate jobs later"),
	U("url_agg_lawsofux_fitts", "https://www.lawsofux.com/fitts-law/", "motor_ergonomics", "B",
	  "Fitts short card — compare to Yorku primary",
	  "shop / newsletter", 1, "queued"),
	U("url_agg_lawsofux_hick", "https://www.lawsofux.com/hicks-law/", "cognitive_load", "B",
	  "Hick short card",
	  "shop", 1, "queued"),
	U("url_agg_lawsofux_miller", "https://www.lawsofux.com/millers-law/", "cognitive_load", "B",
	  "Miller short card",
	  "shop", 1, "queued"),
	U("url_agg_lawsofux_jakob", "https://www.lawsofux.com/jakobs-law/", "general", "B",
	  "Jakob's Law — mental models from other sites",
	  "shop", 1, "queued"),
	U("url_agg_lawsofux_postel", "https://www.lawsofux.com/postels-law/", "forms", "B",
	  "Postel's Law — be liberal in inputs",
	  "shop", 1, "queued"),
	U("url_agg_lawsofux_peakend", "https://www.lawsofux.com/peak-end-rule/", "onboarding", "B",
	  "Peak-end rule for flows",
	  "shop", 1, "queued"),
	U("url_agg_wowmakers", "https://www.wowmakers.com/blog/laws-of-ux-design/", "general", "C",
	  "Aggregator list — use only to find better primaries",
	  "whole listicle as claims", 0, "skipped", "Low signal aggregator"),
]

# === GREENFIELD / STRUCTURAL SITUATIONS (MCP CQs) ===
URLS += [
	U("url_sit_nng_homepage", "https://www.nngroup.com/articles/homepage-design/", "general", "B",
	  "Homepage priorities — not for dashboards",
	  "newsletter", 1, "queued", "CQ-SIT-01 related"),
	U("url_sit_nng_ia_structure", "https://www.nngroup.com/articles/ia-hierarchy/", "settings", "B",
	  "Hierarchy in IA",
	  "newsletter", 1, "queued"),
	U("url_sit_baymard_homepage_design", "https://baymard.com/blog/ecommerce-homepage-ux", "checkout", "B",
	  "Ecommerce homepage UX empirics",
	  "premium", 1, "queued"),
]

# === ACCESSIBILITY PRACTITIONER (non-diluting Absolute support) ===
URLS += [
	U("url_a11y_inclusive_components", "https://inclusive-components.design/", "feedback_systems", "B",
	  "Inclusive component patterns — toggle/tabs/menus a11y",
	  "book sales", 2, "queued"),
	U("url_a11y_govuk_design", "https://design-system.service.gov.uk/", "a11y_absolute", "B",
	  "GOV.UK DS — discover specific components; high a11y bar",
	  "entire hub as one extract", 0, "queued", "Hub — prefer component pages"),
	U("url_a11y_govuk_error_summary", "https://design-system.service.gov.uk/components/error-summary/", "forms", "A",
	  "Error summary pattern for forms",
	  "GOV.UK chrome", 1, "queued"),
	U("url_a11y_govuk_text_input", "https://design-system.service.gov.uk/components/text-input/", "forms", "A",
	  "Text input a11y + hint/error association",
	  "chrome", 1, "queued"),
	U("url_a11y_w3c_aria_authoring", "https://www.w3.org/WAI/ARIA/apg/", "feedback_systems", "A",
	  "APG hub — prefer practice pages already listed",
	  "full catalog dump", 0, "skipped", "Hub"),
]

# === ERROR PREVENTION / SELF-DESCRIPTIVENESS EXTRAS ===
URLS += [
	U("url_err_perpetual", "https://www.perpetualny.com/blog/design-for-error-prevention-solving-problems-before-they-start", "feedback_systems", "B",
	  "Error prevention before recovery",
	  "agency promo", 1, "queued"),
	U("url_err_cedar", "https://cedar.rei.com/patterns/error-handling", "feedback_systems", "B",
	  "Design system error-handling pattern",
	  "REI-specific branding", 1, "queued"),
]

# === ADDITIONAL HIGH-SIGNAL PUBLIC DOCS (own research) ===
URLS += [
	U("url_extra_mdn_forms", "https://developer.mozilla.org/en-US/docs/Learn/Forms", "forms", "B",
	  "HTML forms learning path — constraint validation basics",
	  "full MDN tutorial series dump", 1, "queued"),
	U("url_extra_web_vitals_inp", "https://web.dev/articles/inp", "feedback_systems", "B",
	  "INP responsiveness — ties to perceived feedback latency",
	  "Chrome marketing", 1, "queued"),
	U("url_extra_nng_touch", "https://www.nngroup.com/articles/touch-target-size/", "motor_ergonomics", "A",
	  "Touch target sizing practitioner guidance vs WCAG",
	  "newsletter", 1, "queued", "Compare Absolute vs heuristic"),
	U("url_extra_nng_fitts", "https://www.nngroup.com/articles/fitts-law/", "motor_ergonomics", "B",
	  "NN/g Fitts application notes",
	  "newsletter", 1, "queued"),
	U("url_extra_nng_hick", "https://www.nngroup.com/articles/hick-law/", "cognitive_load", "B",
	  "NN/g Hick application",
	  "newsletter", 1, "queued"),
	U("url_extra_nng_tesler", "https://www.nngroup.com/articles/complexity-reduction/", "cognitive_load", "B",
	  "Complexity reduction / related Tesler themes",
	  "newsletter", 1, "queued"),
	U("url_extra_apple_hig", "https://developer.apple.com/design/human-interface-guidelines", "general", "B",
	  "HIG hub — prefer specific topics (layout, feedback)",
	  "entire HIG dump", 0, "queued", "Hub"),
	U("url_extra_apple_layout", "https://developer.apple.com/design/human-interface-guidelines/layout", "hierarchy_density", "B",
	  "Layout / spacing / hierarchy from HIG",
	  "Apple-only idioms if not transferable", 1, "queued"),
	U("url_extra_apple_feedback", "https://developer.apple.com/design/human-interface-guidelines/feedback", "feedback_systems", "B",
	  "Feedback patterns from HIG",
	  "platform chrome", 1, "queued"),
	U("url_extra_material_layout", "https://m3.material.io/foundations/layout/understanding-layout/overview", "hierarchy_density", "B",
	  "Material layout understanding",
	  "Android-specific", 1, "queued"),
	U("url_extra_wcag_nontext", "https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast", "a11y_absolute", "A",
	  "Non-text contrast 3:1 for UI components",
	  "unrelated SC", 1, "queued"),
	U("url_extra_wcag_status", "https://www.w3.org/WAI/WCAG22/Understanding/status-messages", "feedback_systems", "A",
	  "Status messages without focus steal",
	  "unrelated", 1, "queued"),
]

# === MORE NN/g + STANDARDS (coverage expansion) ===
URLS += [
	U("url_nng_heuristics", "https://www.nngroup.com/articles/ten-usability-heuristics/", "feedback_systems", "A",
	  "10 usability heuristics — map to detect/when fields carefully",
	  "poster shop / newsletter", 3, "queued", "Classic — split into few cards max"),
	U("url_nng_consistency", "https://www.nngroup.com/articles/consistency-and-standards/", "feedback_systems", "B",
	  "Consistency and standards heuristic deep-dive",
	  "newsletter", 1, "queued"),
	U("url_nng_recognition", "https://www.nngroup.com/articles/recognition-and-recall/", "cognitive_load", "B",
	  "Recognition over recall",
	  "newsletter", 1, "queued"),
	U("url_nng_flexibility", "https://www.nngroup.com/articles/flexibility-efficiency-expertise/", "cognitive_load", "B",
	  "Accelerators for experts vs novices",
	  "newsletter", 1, "queued"),
	U("url_nng_minimalist", "https://www.nngroup.com/articles/minimize-cognitive-load/", "cognitive_load", "B",
	  "Minimize cognitive load techniques",
	  "newsletter", 1, "queued"),
	U("url_nng_forms_labels", "https://www.nngroup.com/articles/form-design-placeholders/", "forms", "A",
	  "Placeholders vs labels — do not use placeholder as only label",
	  "newsletter", 1, "queued"),
	U("url_nng_password", "https://www.nngroup.com/articles/stop-password-masking/", "forms", "B",
	  "Password masking UX tradeoffs",
	  "newsletter", 1, "queued"),
	U("url_nng_checkbox_radio", "https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/", "forms", "A",
	  "Checkbox vs radio decision rules",
	  "newsletter", 1, "queued"),
	U("url_nng_dropdowns", "https://www.nngroup.com/articles/drop-down-menus/", "forms", "B",
	  "When dropdowns hurt Hick / Fitts",
	  "newsletter", 1, "queued"),
	U("url_nng_modal", "https://www.nngroup.com/articles/modal-nonmodal-dialog/", "feedback_systems", "A",
	  "Modal vs nonmodal; when dialogs block",
	  "newsletter", 1, "queued"),
	U("url_nng_toast", "https://www.nngroup.com/articles/toast/", "feedback_systems", "B",
	  "Toast notification timing and discoverability issues",
	  "newsletter", 1, "queued"),
	U("url_nng_skeleton", "https://www.nngroup.com/articles/skeleton-screens/", "feedback_systems", "B",
	  "Skeleton screens vs spinners for perceived performance",
	  "newsletter", 1, "queued"),
	U("url_nng_empty", "https://www.nngroup.com/articles/empty-state/", "onboarding", "B",
	  "Empty states as onboarding opportunity",
	  "newsletter", 1, "queued"),
	U("url_nng_wizard", "https://www.nngroup.com/articles/wizards/", "onboarding", "B",
	  "When wizards help multi-step tasks",
	  "newsletter", 1, "queued"),
	U("url_nng_cards", "https://www.nngroup.com/articles/cards-component/", "hierarchy_density", "B",
	  "When cards help grouping vs clutter",
	  "newsletter", 1, "queued"),
	U("url_nng_whitespace", "https://www.nngroup.com/articles/whitespace/", "hierarchy_density", "A",
	  "Whitespace for grouping and hierarchy",
	  "newsletter", 1, "queued"),
	U("url_nng_scan", "https://www.nngroup.com/articles/how-users-read-on-the-web/", "reading_flow", "A",
	  "Users scan; design for scannability",
	  "newsletter", 1, "queued"),
	U("url_nng_cta", "https://www.nngroup.com/articles/call-to-action/", "onboarding", "B",
	  "CTA clarity and placement",
	  "newsletter", 1, "queued"),
	U("url_wcag_keyboard", "https://www.w3.org/WAI/WCAG22/Understanding/keyboard", "a11y_absolute", "A",
	  "Keyboard operable Absolute",
	  "unrelated SC", 1, "queued"),
	U("url_wcag_name_role", "https://www.w3.org/WAI/WCAG22/Understanding/name-role-value", "a11y_absolute", "A",
	  "Name Role Value for custom controls",
	  "unrelated", 1, "queued"),
	U("url_wcag_labels", "https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions", "forms", "A",
	  "Labels or instructions Absolute for inputs",
	  "unrelated", 1, "queued"),
	U("url_wcag_error_ident", "https://www.w3.org/WAI/WCAG22/Understanding/error-identification", "forms", "A",
	  "Error identification Absolute",
	  "unrelated", 1, "queued"),
	U("url_wcag_error_suggest", "https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion", "forms", "A",
	  "Error suggestion Absolute",
	  "unrelated", 1, "queued"),
	U("url_wcag_focus_visible", "https://www.w3.org/WAI/WCAG22/Understanding/focus-visible", "a11y_absolute", "A",
	  "Focus visible Absolute",
	  "unrelated", 1, "queued"),
	U("url_wcag_reflow", "https://www.w3.org/WAI/WCAG22/Understanding/reflow", "a11y_absolute", "B",
	  "Reflow 320 CSS px — layout without horizontal scroll",
	  "unrelated", 1, "queued"),
	U("url_baymard_account", "https://baymard.com/learn/account-creation", "checkout", "B",
	  "Account creation vs guest friction",
	  "premium", 1, "queued"),
	U("url_baymard_mobile", "https://baymard.com/research/mobile-ecommerce", "checkout", "B",
	  "Mobile ecommerce UX empirics",
	  "premium", 1, "queued"),
	U("url_carbon_data_table", "https://carbondesignsystem.com/components/data-table/usage/", "hierarchy_density", "B",
	  "Dense data table usage patterns",
	  "API props dump", 1, "queued"),
	U("url_carbon_form", "https://carbondesignsystem.com/components/form/usage/", "forms", "A",
	  "Carbon form usage / validation patterns",
	  "API dump", 1, "queued"),
	U("url_polaris_textfield", "https://polaris.shopify.com/components/selection-and-input/text-field", "forms", "B",
	  "Polaris text field patterns / error props",
	  "SPA shell", 1, "queued"),
	U("url_polaris_banner", "https://polaris.shopify.com/components/feedback-indicators/banner", "feedback_systems", "B",
	  "Banner feedback patterns",
	  "SPA shell", 1, "queued"),
	U("url_atlassian_forms", "https://atlassian.design/components/form/examples", "forms", "B",
	  "ADS form examples / patterns",
	  "storybook chrome", 1, "queued"),
	U("url_govuk_button", "https://design-system.service.gov.uk/components/button/", "motor_ergonomics", "B",
	  "GOV.UK button sizing / primary vs secondary",
	  "chrome", 1, "queued"),
	U("url_govuk_checkboxes", "https://design-system.service.gov.uk/components/checkboxes/", "forms", "B",
	  "Checkbox grouping patterns",
	  "chrome", 1, "queued"),
	U("url_mdn_constraint_validation", "https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation", "forms", "B",
	  "Native constraint validation API meanings",
	  "engine-specific digressions", 1, "queued"),
	U("url_webaim_keyboard", "https://webaim.org/techniques/keyboard/", "a11y_absolute", "B",
	  "Keyboard accessibility techniques",
	  "training ads", 1, "queued"),
	U("url_webaim_skipnav", "https://webaim.org/techniques/skipnav/", "a11y_absolute", "B",
	  "Skip navigation pattern",
	  "ads", 1, "queued"),
	U("url_smashing_forms", "https://www.smashingmagazine.com/2011/11/ten-guidelines-for-better-form-usability/", "forms", "B",
	  "Classic form usability guidelines",
	  "comments", 1, "queued"),
	U("url_smashing_inline_validation", "https://www.smashingmagazine.com/2022/09/inline-validation-ux-forms/", "forms", "B",
	  "Inline validation UX patterns",
	  "comments", 1, "queued"),
	U("url_alistapart_responsive", "https://alistapart.com/article/responsive-web-design/", "general", "C",
	  "Historical RWD — only if layout foundations needed",
	  "dated examples", 1, "queued"),
	U("url_pair_mental_models", "https://pair.withgoogle.com/guidebook/patterns", "agentic_ux", "A",
	  "PAIR patterns index — pick mental models / explainability",
	  "entire guidebook dump", 2, "queued"),
	U("url_lawsofux_aesthetic", "https://www.lawsofux.com/aesthetic-usability-effect/", "aesthetic_usability", "B",
	  "Aesthetic-usability short card",
	  "shop", 1, "queued"),
	U("url_lawsofux_doherty", "https://www.lawsofux.com/doherty-threshold/", "feedback_systems", "B",
	  "Doherty threshold ~400ms productivity",
	  "shop", 1, "queued"),
	U("url_lawsofux_serial", "https://www.lawsofux.com/serial-position-effect/", "cognitive_load", "B",
	  "Serial position — first/last items remembered",
	  "shop", 1, "queued"),
	U("url_nng_destructive", "https://www.nngroup.com/articles/confirmation-dialog/", "feedback_systems", "A",
	  "Confirmation dialogs for destructive actions; beneficial friction",
	  "newsletter", 1, "queued", "Fitts when-not for destructive"),
	U("url_nng_undo", "https://www.nngroup.com/articles/undo/", "feedback_systems", "A",
	  "Undo as safer than confirm spam",
	  "newsletter", 1, "queued"),
]

# === BATCH 2 — APG widgets, more WCAG, denser DS pages ===
URLS += [
	U("url_apg_dialog", "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/", "feedback_systems", "A",
	  "Modal dialog keyboard/focus trap expectations",
	  "full APG catalog", 1, "queued"),
	U("url_apg_menu", "https://www.w3.org/WAI/ARIA/apg/patterns/menu/", "motor_ergonomics", "A",
	  "Menu keyboard patterns; related to Steering paths",
	  "catalog", 1, "queued"),
	U("url_apg_tabs", "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/", "hierarchy_density", "B",
	  "Tabs pattern a11y / when tabs vs pages",
	  "catalog", 1, "queued"),
	U("url_apg_combobox", "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/", "forms", "A",
	  "Combobox a11y — complex input pattern",
	  "catalog", 1, "queued"),
	U("url_apg_switch", "https://www.w3.org/WAI/ARIA/apg/patterns/switch/", "forms", "B",
	  "Switch vs checkbox semantics",
	  "catalog", 1, "queued"),
	U("url_apg_tooltip", "https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/", "feedback_systems", "B",
	  "Tooltip a11y limitations — not for essential info",
	  "catalog", 1, "queued"),
	U("url_wcag_dragging", "https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements", "a11y_absolute", "B",
	  "Dragging movements — single pointer alternative",
	  "unrelated", 1, "queued"),
	U("url_wcag_accessible_auth", "https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum", "forms", "B",
	  "Accessible authentication — reduce cognitive tests",
	  "unrelated", 1, "queued"),
	U("url_wcag_consistent_help", "https://www.w3.org/WAI/WCAG22/Understanding/consistent-help", "settings", "B",
	  "Consistent help mechanism placement",
	  "unrelated", 1, "queued"),
	U("url_wcag_redundant_entry", "https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry", "forms", "A",
	  "Do not ask same info twice in a process",
	  "unrelated", 1, "queued"),
	U("url_nng_pricing", "https://www.nngroup.com/articles/pricing-page/", "cognitive_load", "B",
	  "Pricing page choice overload / Hick",
	  "newsletter", 1, "queued"),
	U("url_nng_filters", "https://www.nngroup.com/articles/filters-vs-facets/", "checkout", "B",
	  "Filters vs facets for product findability",
	  "newsletter", 1, "queued"),
	U("url_nng_search", "https://www.nngroup.com/articles/search-visible/", "checkout", "B",
	  "Make search visible / discoverable",
	  "newsletter", 1, "queued"),
	U("url_nng_pagination", "https://www.nngroup.com/articles/infinite-scrolling/", "hierarchy_density", "B",
	  "Infinite scroll vs pagination tradeoffs",
	  "newsletter", 1, "queued"),
	U("url_nng_mobile_nav", "https://www.nngroup.com/articles/mobile-navigation/", "hierarchy_density", "B",
	  "Mobile navigation patterns",
	  "newsletter", 1, "queued"),
	U("url_nng_sticky", "https://www.nngroup.com/articles/sticky-headers/", "hierarchy_density", "B",
	  "Sticky headers — when help vs obscure focus",
	  "newsletter", 1, "queued", "Ties to focus-not-obscured"),
	U("url_nng_accordions", "https://www.nngroup.com/articles/accordions-complex-content/", "cognitive_load", "A",
	  "Accordions for progressive disclosure",
	  "newsletter", 1, "queued"),
	U("url_nng_tooltip_use", "https://www.nngroup.com/articles/tooltip-guidelines/", "feedback_systems", "B",
	  "Tooltip guidelines — not for primary info",
	  "newsletter", 1, "queued"),
	U("url_nng_icons", "https://www.nngroup.com/articles/icon-usability/", "feedback_systems", "B",
	  "Icon usability / labeling",
	  "newsletter", 1, "queued"),
	U("url_nng_colorblind", "https://www.nngroup.com/articles/color-enhance/", "a11y_absolute", "B",
	  "Do not rely on color alone",
	  "newsletter", 1, "queued"),
	U("url_carbon_notification", "https://carbondesignsystem.com/components/notification/usage/", "feedback_systems", "B",
	  "Notification kinds / when toast vs inline",
	  "API dump", 1, "queued"),
	U("url_carbon_modal", "https://carbondesignsystem.com/components/modal/usage/", "feedback_systems", "B",
	  "Modal usage density enterprise",
	  "API dump", 1, "queued"),
	U("url_carbon_button", "https://carbondesignsystem.com/components/button/usage/", "motor_ergonomics", "B",
	  "Button kinds / sizing enterprise",
	  "API dump", 1, "queued"),
	U("url_slds_touch", "https://www.lightningdesignsystem.com/design-tokens/#category-component-sizing", "motor_ergonomics", "B",
	  "SLDS sizing tokens if page loads",
	  "blocked pages", 1, "queued"),
	U("url_polaris_layout", "https://polaris.shopify.com/components/layout-and-structure", "hierarchy_density", "B",
	  "Polaris layout structure components",
	  "SPA shell", 1, "queued"),
	U("url_atlassian_spacing", "https://atlassian.design/foundations/spacing", "hierarchy_density", "A",
	  "ADS spacing foundations",
	  "chrome", 1, "queued"),
	U("url_atlassian_color", "https://atlassian.design/foundations/color", "design_tokens", "A",
	  "ADS color foundations / semantic roles",
	  "chrome", 1, "queued"),
	U("url_govuk_error_message", "https://design-system.service.gov.uk/components/error-message/", "forms", "A",
	  "Per-field error message pattern",
	  "chrome", 1, "queued"),
	U("url_govuk_fieldset", "https://design-system.service.gov.uk/components/fieldset/", "forms", "B",
	  "Fieldset grouping related inputs",
	  "chrome", 1, "queued"),
	U("url_govuk_radios", "https://design-system.service.gov.uk/components/radios/", "forms", "B",
	  "Radio grouping patterns",
	  "chrome", 1, "queued"),
	U("url_mdn_aria_live", "https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions", "feedback_systems", "B",
	  "Live regions for status without focus move",
	  "MDN nav", 1, "queued"),
	U("url_webaim_forms", "https://webaim.org/techniques/forms/", "forms", "A",
	  "Accessible form techniques",
	  "training ads", 1, "queued"),
	U("url_baymard_cart", "https://baymard.com/learn/cart-page", "checkout", "B",
	  "Cart page UX empirics",
	  "premium", 1, "queued"),
	U("url_baymard_shipping", "https://baymard.com/learn/shipping", "checkout", "B",
	  "Shipping step friction empirics",
	  "premium", 1, "queued"),
	U("url_nng_onboarding_desktop", "https://www.nngroup.com/articles/user-onboarding/", "onboarding", "A",
	  "User onboarding patterns overview",
	  "newsletter", 2, "queued"),
	U("url_nng_mental_models", "https://www.nngroup.com/articles/mental-models/", "general", "B",
	  "Mental models — Jakob adjacent",
	  "newsletter", 1, "queued"),
	U("url_nng_learnability", "https://www.nngroup.com/articles/usability-101-introduction-to-usability/", "general", "B",
	  "Usability 101 dimensions learnability efficiency",
	  "newsletter", 1, "queued"),
	U("url_lawsofux_vonrestorff", "https://www.lawsofux.com/von-restorff-effect/", "hierarchy_density", "B",
	  "Isolation effect for primary CTA emphasis",
	  "shop", 1, "queued"),
	U("url_lawsofux_occam", "https://www.lawsofux.com/occams-razor/", "cognitive_load", "C",
	  "Prefer simpler designs — weak alone",
	  "shop", 1, "queued"),
	U("url_inclusive_toggle", "https://inclusive-components.design/toggle-button/", "forms", "B",
	  "Inclusive toggle button pattern",
	  "book promo", 1, "queued"),
	U("url_inclusive_cards", "https://inclusive-components.design/cards/", "hierarchy_density", "B",
	  "Inclusive cards pattern",
	  "book promo", 1, "queued"),
	U("url_material_a11y", "https://m3.material.io/foundations/accessibility", "a11y_absolute", "B",
	  "Material a11y foundations cross-check",
	  "Android-only", 1, "queued"),
	U("url_apple_accessibility", "https://developer.apple.com/design/human-interface-guidelines/accessibility", "a11y_absolute", "B",
	  "Apple HIG accessibility — transferable principles only",
	  "platform APIs", 1, "queued"),
	U("url_freecodecamp_academic_ux", "https://www.freecodecamp.org/news/how-to-apply-academic-theories-to-human-centered-web-design-handbook/", "general", "B",
	  "Academic theories applied to web design handbook",
	  "long tutorial filler", 2, "queued"),
	U("url_cxl_forms_general", "https://cxl.com/blog/form-design/", "forms", "B",
	  "CXL form design research roundup",
	  "course CTAs", 1, "queued"),
	U("url_reform_layout", "https://www.reform.app/blog/research-how-layout-affects-form-completion-rates", "forms", "B",
	  "Layout affect on form completion research summary",
	  "product promo", 1, "queued"),
]

# === SCALE BATCH — frontend gaps (typography, motion, auth, tables, search) ===
URLS += [
	U("url_mdn_typography", "https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals", "typography", "A",
	  "Line height, font-size scale, readable line length",
	  "MDN nav chrome", 1, "queued", "Typography gap — web fundamentals"),
	U("url_nng_typography", "https://www.nngroup.com/articles/typography-terms-ux/", "typography", "A",
	  "Typography terms for UX; legibility vs readability",
	  "newsletter", 1, "queued"),
	U("url_smashing_typography", "https://www.smashingmagazine.com/2020/07/css-typography-rules/", "typography", "B",
	  "CSS typography rules; scale and rhythm",
	  "author bio", 1, "queued"),
	U("url_material_type", "https://m3.material.io/styles/typography/overview", "typography", "B",
	  "Material type scale roles",
	  "Android-only examples", 1, "queued"),
	U("url_wcag_text_spacing", "https://www.w3.org/WAI/WCAG22/Understanding/text-spacing", "typography", "A",
	  "WCAG text spacing overrides for readability",
	  "unrelated SC", 1, "queued"),
	U("url_mdn_prefers_reduced_motion", "https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion", "motion", "A",
	  "prefers-reduced-motion media query usage",
	  "MDN nav", 1, "queued"),
	U("url_nng_animation", "https://www.nngroup.com/articles/animation-usability/", "motion", "A",
	  "When animation helps vs distracts; duration guidance",
	  "newsletter", 1, "queued"),
	U("url_wcag_animation", "https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions", "motion", "A",
	  "WCAG 2.2 animation from interactions",
	  "AAA variants", 1, "queued"),
	U("url_material_motion", "https://m3.material.io/styles/motion/overview", "motion", "B",
	  "Motion duration/easing tokens",
	  "platform-specific", 1, "queued"),
	U("url_carbon_motion", "https://carbondesignsystem.com/guidelines/motion/overview/", "motion", "B",
	  "Enterprise motion guidelines",
	  "API dump", 1, "queued"),
	U("url_wcag_auth_labels", "https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions", "auth", "A",
	  "Labels for login inputs",
	  "unrelated SC", 1, "queued", "Auth/guards gap"),
	U("url_nng_login", "https://www.nngroup.com/articles/login-pages/", "auth", "A",
	  "Login page UX patterns",
	  "newsletter", 1, "queued"),
	U("url_webaim_captcha", "https://webaim.org/techniques/captcha/", "auth", "B",
	  "Accessible CAPTCHA alternatives",
	  "training ads", 1, "queued"),
	U("url_govuk_sign_in", "https://design-system.service.gov.uk/patterns/sign-in/", "auth", "A",
	  "Sign-in pattern; session recovery",
	  "chrome", 1, "queued"),
	U("url_nng_password_auth", "https://www.nngroup.com/articles/password-creation/", "auth", "B",
	  "Password creation UX",
	  "newsletter", 1, "queued"),
	U("url_carbon_data_table", "https://carbondesignsystem.com/components/data-table/usage/", "data_tables", "A",
	  "Data table sorting, filtering, batch actions",
	  "API dump", 2, "queued", "Tables/grids gap"),
	U("url_polaris_index_table", "https://polaris.shopify.com/components/tables/index-table", "data_tables", "B",
	  "Index table patterns for admin UIs",
	  "SPA shell", 1, "queued"),
	U("url_nng_filtering", "https://www.nngroup.com/articles/filters-vs-facets/", "data_tables", "A",
	  "Filters vs facets for large datasets",
	  "newsletter", 1, "queued"),
	U("url_nng_pagination", "https://www.nngroup.com/articles/ecommerce-search/", "data_tables", "B",
	  "Search and pagination patterns",
	  "newsletter", 1, "queued"),
	U("url_atlassian_table", "https://atlassian.design/components/table/examples", "data_tables", "B",
	  "ADS table examples",
	  "chrome", 1, "queued"),
	U("url_nng_search_visible", "https://www.nngroup.com/articles/search-visible-and-simple/", "search", "A",
	  "Search box visibility and placement",
	  "newsletter", 1, "queued"),
	U("url_baymard_search", "https://baymard.com/blog/ecommerce-search", "search", "B",
	  "Ecommerce search UX empirics",
	  "premium", 1, "queued"),
	U("url_nng_autocomplete", "https://www.nngroup.com/articles/autocomplete/", "search", "A",
	  "Autocomplete/typeahead UX",
	  "newsletter", 1, "queued"),
	U("url_w3c_settings_pattern", "https://www.w3.org/WAI/ARIA/apg/patterns/", "settings", "B",
	  "APG patterns applicable to settings panels",
	  "full catalog", 1, "queued", "Settings IA supplement"),
]


def main() -> None:
	# de-dupe by id
	seen: set[str] = set()
	unique: list[dict] = []
	for row in URLS:
		if row["id"] in seen:
			continue
		seen.add(row["id"])
		unique.append(row)

	doc = {
		"version": 1,
		"updated": "2026-07-20",
		"description": (
			"Curated high-signal URL queue for UX KB pipeline. "
			"Sources: Google AI UX Knowledge Engine Research ranked bibliography, "
			"ForOpenCode RESOURCE_INDEX, and selective public primaries for MCP CQs. "
			"Workers must obey get/skip. Prefer specific pages over hubs. "
			"Use Wayback URLs when live hosts 403."
		),
		"policy": {
			"no_free_discovery": True,
			"runtime_only_accepted_principles": True,
			"frozen_topics": ["a11y_absolute"],
			"prefer_primary_over_aggregator": True,
		},
		"stats": {
			"total_urls": len(unique),
			"by_priority": {},
			"by_topic": {},
			"by_status": {},
		},
		"urls": unique,
	}
	for row in unique:
		doc["stats"]["by_priority"][row["priority"]] = (
			doc["stats"]["by_priority"].get(row["priority"], 0) + 1
		)
		doc["stats"]["by_topic"][row["topic"]] = (
			doc["stats"]["by_topic"].get(row["topic"], 0) + 1
		)
		doc["stats"]["by_status"][row["status"]] = (
			doc["stats"]["by_status"].get(row["status"], 0) + 1
		)

	OUT.write_text(
		yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100),
		encoding="utf-8",
	)
	print(f"Wrote {len(unique)} urls -> {OUT}")
	print("by_priority", doc["stats"]["by_priority"])
	print("by_topic", doc["stats"]["by_topic"])
	print("by_status", doc["stats"]["by_status"])


if __name__ == "__main__":
	main()
