"""Static Hero Patterns catalog — names from heropatterns.com / hero-patterns npm."""

from __future__ import annotations

# Curated from hero-patterns@2.1.0 ESM exports (and matching heropatterns.com names).
PATTERN_CATALOG: tuple[dict[str, str], ...] = tuple(
	{
		"id": slug,
		"title": title,
		"npm_export": export,
	}
	for slug, title, export in (
		("anchors-away", "Anchors Away", "anchorsAway"),
		("architect", "Architect", "architect"),
		("autumn", "Autumn", "autumn"),
		("aztec", "Aztec", "aztec"),
		("bamboo", "Bamboo", "bamboo"),
		("bank-note", "Bank Note", "bankNote"),
		("bathroom-floor", "Bathroom Floor", "bathroomFloor"),
		("bevel-circle", "Bevel Circle", "bevelCircle"),
		("boxes", "Boxes", "boxes"),
		("brick-wall", "Brick Wall", "brickWall"),
		("bubbles", "Bubbles", "bubbles"),
		("cage", "Cage", "cage"),
		("charlie-brown", "Charlie Brown", "charlieBrown"),
		("church-on-sunday", "Church On Sunday", "churchOnSunday"),
		("circles-and-squares", "Circles And Squares", "circlesAndSquares"),
		("circuit-board", "Circuit Board", "circuitBoard"),
		("connections", "Connections", "connections"),
		("cork-screw", "Cork Screw", "corkScrew"),
		("current", "Current", "current"),
		("curtain", "Curtain", "curtain"),
		("cutout", "Cutout", "cutout"),
		("death-star", "Death Star", "deathStar"),
		("diagonal-lines", "Diagonal Lines", "diagonalLines"),
		("diagonal-stripes", "Diagonal Stripes", "diagonalStripes"),
		("dominos", "Dominos", "dominos"),
		("endless-clouds", "Endless Clouds", "endlessClouds"),
		("eyes", "Eyes", "eyes"),
		("falling-triangles", "Falling Triangles", "fallingTriangles"),
		("fancy-rectangles", "Fancy Rectangles", "fancyRectangles"),
		("flipped-diamonds", "Flipped Diamonds", "flippedDiamonds"),
		("floating-cogs", "Floating Cogs", "floatingCogs"),
		("floor-tile", "Floor Tile", "floorTile"),
		("formal-invitation", "Formal Invitation", "formalInvitation"),
		("four-point-stars", "Four Point Stars", "fourPointStars"),
		("glamorous", "Glamorous", "glamorous"),
		("graph-paper", "Graph Paper", "graphPaper"),
		("groovy", "Groovy", "groovy"),
		("happy-intersection", "Happy Intersection", "happyIntersection"),
		("heavy-rain", "Heavy Rain", "heavyRain"),
		("hexagons", "Hexagons", "hexagons"),
		("hideout", "Hideout", "hideout"),
		("houndstooth", "Houndstooth", "houndstooth"),
		("i-like-food", "I Like Food", "iLikeFood"),
		("intersecting-circles", "Intersecting Circles", "intersectingCircles"),
		("jigsaw", "Jigsaw", "jigsaw"),
		("jupiter", "Jupiter", "jupiter"),
		("kiwi", "Kiwi", "kiwi"),
		("leaf", "Leaf", "leaf"),
		("lines-in-motion", "Lines In Motion", "linesInMotion"),
		("lips", "Lips", "lips"),
		("lisbon", "Lisbon", "lisbon"),
		("melt", "Melt", "melt"),
		("moroccan", "Moroccan", "moroccan"),
		("morphing-diamonds", "Morphing Diamonds", "morphingDiamonds"),
		("overcast", "Overcast", "overcast"),
		("overlapping-circles", "Overlapping Circles", "overlappingCircles"),
		("overlapping-diamonds", "Overlapping Diamonds", "overlappingDiamonds"),
		("overlapping-hexagons", "Overlapping Hexagons", "overlappingHexagons"),
		("parkay-floor", "Parkay Floor", "parkayFloor"),
		("piano-man", "Piano Man", "pianoMan"),
		("pie-factory", "Pie Factory", "pieFactory"),
		("pixel-dots", "Pixel Dots", "pixelDots"),
		("plus", "Plus", "plus"),
		("polka-dots", "Polka Dots", "polkaDots"),
		("rails", "Rails", "rails"),
		("rain", "Rain", "rain"),
		("random-shapes", "Random Shapes", "randomShapes"),
		("rounded-plus-connected", "Rounded Plus Connected", "roundedPlusConnected"),
		("signal", "Signal", "signal"),
		("skulls", "Skulls", "skulls"),
		("slanted-stars", "Slanted Stars", "slantedStars"),
		("squares", "Squares", "squares"),
		("squares-in-squares", "Squares In Squares", "squaresInSquares"),
		("stamp-collection", "Stamp Collection", "stampCollection"),
		("steel-beams", "Steel Beams", "steelBeams"),
		("stripes", "Stripes", "stripes"),
		("temple", "Temple", "temple"),
		("texture", "Texture", "texture"),
		("tic-tac-toe", "Tic Tac Toe", "ticTacToe"),
		("tiny-checkers", "Tiny Checkers", "tinyCheckers"),
		("topography", "Topography", "topography"),
		("volcano-lamp", "Volcano Lamp", "volcanoLamp"),
		("wallpaper", "Wallpaper", "wallpaper"),
		("wiggle", "Wiggle", "wiggle"),
		("x-equals", "X Equals", "xEquals"),
		("yyy", "YYY", "yyy"),
		("zig-zag", "Zig Zag", "zigZag"),
	)
)
