"""Seed SEO Knowledge Graph provider nodes — free-first, user-owned data."""
from __future__ import annotations

from navigation.seo_intelligence.models import SeoProviderMeta


SEED_PROVIDERS: dict[str, SeoProviderMeta] = {
	'search-console': SeoProviderMeta(
		provider_id='search-console',
		display_name='Google Search Console',
		priority_tier=0,
		auth_required=True,
		user_owned_data=True,
		free_tier=True,
		capabilities=[
			'search_queries',
			'clicks',
			'impressions',
			'ctr',
			'average_position',
			'indexed_pages',
			'crawl_issues',
			'url_inspection',
			'sitemaps',
			'coverage',
			'core_web_vitals',
		],
		auth_notes='OAuth 2.0 — user Google account; Search Console API v1',
		rate_limit_notes='Google API quotas per project — batch requests',
		official_docs_url='https://developers.google.com/webmaster-tools/v1/api_reference_index',
		implementation_status='live',
	),
	'analytics-ga4': SeoProviderMeta(
		provider_id='analytics-ga4',
		display_name='Google Analytics 4',
		priority_tier=0,
		auth_required=True,
		user_owned_data=True,
		free_tier=True,
		capabilities=[
			'sessions',
			'users',
			'conversions',
			'traffic_sources',
			'landing_pages',
			'engagement',
			'bounce_metrics',
			'devices',
			'geography',
		],
		auth_notes='OAuth 2.0 — user Google account; GA4 Data API',
		rate_limit_notes='GA4 Data API quotas — use batchRunReports',
		official_docs_url='https://developers.google.com/analytics/devguides/reporting/data/v1',
		implementation_status='live',
	),
	'bing-webmaster': SeoProviderMeta(
		provider_id='bing-webmaster',
		display_name='Bing Webmaster Tools',
		priority_tier=2,
		auth_required=True,
		user_owned_data=True,
		free_tier=True,
		capabilities=['search_performance', 'crawl_issues', 'sitemaps', 'url_inspection'],
		auth_notes='API key — optional; only when user connects Bing',
		official_docs_url='https://learn.microsoft.com/en-us/bingwebmaster/',
		implementation_status='research',
	),
	'librecrawl': SeoProviderMeta(
		provider_id='librecrawl',
		display_name='LibreCrawl',
		priority_tier=0,
		auth_required=False,
		user_owned_data=False,
		free_tier=True,
		capabilities=[
			'technical_crawl',
			'broken_links',
			'redirect_chains',
			'duplicate_pages',
			'canonicals',
			'robots',
			'sitemap',
			'schema',
			'internal_links',
			'js_rendering',
			'crawl_depth',
			'status_codes',
		],
		auth_notes='Self-hosted or local LibreCrawl instance — no internet-scale crawler in MCP',
		official_docs_url='https://github.com/librecrawl/librecrawl',
		implementation_status='live',
	),
	'lighthouse': SeoProviderMeta(
		provider_id='lighthouse',
		display_name='Lighthouse / PageSpeed Insights',
		priority_tier=0,
		auth_required=False,
		user_owned_data=False,
		free_tier=True,
		capabilities=[
			'performance',
			'accessibility',
			'best_practices',
			'seo_score',
			'core_web_vitals',
		],
		auth_notes='PageSpeed Insights API (optional key) or local Lighthouse CLI',
		rate_limit_notes='PSI API daily quota without key; prefer local for CI',
		official_docs_url='https://developers.google.com/speed/docs/insights/v5/get-started',
		implementation_status='live',
	),
	'browser': SeoProviderMeta(
		provider_id='browser',
		display_name='Browser Intelligence (Visual Browser)',
		priority_tier=1,
		auth_required=False,
		user_owned_data=False,
		free_tier=True,
		capabilities=[
			'rendering_verification',
			'hydration',
			'navigation',
			'client_side_errors',
			'layout_issues',
			'javascript_errors',
		],
		auth_notes='Reuses visual_browser_intelligence via adapter — not a duplicate browser',
		official_docs_url='https://github.com/',
		implementation_status='live',
	),
	'openseo': SeoProviderMeta(
		provider_id='openseo',
		display_name='OpenSEO',
		priority_tier=1,
		auth_required=False,
		user_owned_data=False,
		free_tier=False,
		capabilities=[
			'search_queries',
			'index_status',
			'keyword_research',
			'serp_analysis',
			'domain_intelligence',
			'backlinks',
			'rank_tracking',
			'ai_visibility',
		],
		auth_notes='Self-hosted (Docker/Cloudflare) or openseo.so — MCP URL via OPENSEO_BASE_URL; OPENSEO_PROJECT_ID required',
		rate_limit_notes='Free GSC tools (performance, URL inspection); DataForSEO API is pay-as-you-go per request',
		official_docs_url='https://github.com/every-app/open-seo',
		implementation_status='partial',
	),
}
