"""Seed Resource Graph provider nodes — commercial-use confirmed only by default."""
from __future__ import annotations

from navigation.resource_intelligence.models import (
	LicenseProfile,
	ResourceCategory,
	ResourceProviderMeta,
)


def _lic(**kwargs: object) -> LicenseProfile:
	return LicenseProfile(**kwargs)  # type: ignore[arg-type]


# Active providers: commercial_use=True, excluded=False, revalidate before adapters.
SEED_PROVIDERS: dict[str, ResourceProviderMeta] = {
	# --- Icons (MIT/ISC/Apache — commercial by default) ---
	'iconify': ResourceProviderMeta(
		provider_id='iconify',
		display_name='Iconify',
		categories=[ResourceCategory.ICON],
		priority_tier=0,
		api_available=True,
		self_hostable=True,
		license=_lic(
			spdx_id='MIT',
			commercial_use=True,
			attribution_required=False,
			redistribution_allowed=True,
			mcp_download_allowed=True,
			ai_training_allowed=True,
			self_hostable=True,
			notes=['Adapter must skip non-commercial icon collections (e.g. CC-BY-NC)'],
			source_url='https://iconify.design/docs/licenses.html',
		),
	),
	'lucide': ResourceProviderMeta(
		provider_id='lucide',
		display_name='Lucide',
		categories=[ResourceCategory.ICON],
		priority_tier=0,
		self_hostable=True,
		license=_lic(spdx_id='ISC', commercial_use=True, mcp_download_allowed=True, self_hostable=True, source_url='https://lucide.dev/license'),
	),
	'heroicons': ResourceProviderMeta(
		provider_id='heroicons',
		display_name='Heroicons',
		categories=[ResourceCategory.ICON],
		priority_tier=0,
		self_hostable=True,
		license=_lic(spdx_id='MIT', commercial_use=True, mcp_download_allowed=True, self_hostable=True, source_url='https://github.com/tailwindlabs/heroicons/blob/master/LICENSE'),
	),
	'tabler-icons': ResourceProviderMeta(
		provider_id='tabler-icons',
		display_name='Tabler Icons',
		categories=[ResourceCategory.ICON],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='MIT', commercial_use=True, mcp_download_allowed=True, self_hostable=True, source_url='https://github.com/tabler/tabler-icons/blob/main/LICENSE'),
	),
	'phosphor-icons': ResourceProviderMeta(
		provider_id='phosphor-icons',
		display_name='Phosphor Icons',
		categories=[ResourceCategory.ICON],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='MIT', commercial_use=True, mcp_download_allowed=True, self_hostable=True, source_url='https://github.com/phosphor-icons/core/blob/main/LICENSE'),
	),
	'remix-icon': ResourceProviderMeta(
		provider_id='remix-icon',
		display_name='Remix Icon',
		categories=[ResourceCategory.ICON],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='Apache-2.0', commercial_use=True, mcp_download_allowed=True, self_hostable=True, source_url='https://github.com/Remix-Design/RemixIcon/blob/master/License'),
	),
	# --- Fonts (free commercial — OFL / Apache / ITF FFL) ---
	'fontsource': ResourceProviderMeta(
		provider_id='fontsource',
		display_name='Fontsource',
		categories=[ResourceCategory.FONT],
		priority_tier=0,
		self_hostable=True,
		license=_lic(
			spdx_id='OFL-1.1',
			commercial_use=True,
			mcp_download_allowed=True,
			self_hostable=True,
			notes=['1500+ npm packages; per-family SPDX (OFL, Apache-2.0, UFL); mirrors Google Fonts'],
			source_url='https://fontsource.org',
		),
	),
	'bunny-fonts': ResourceProviderMeta(
		provider_id='bunny-fonts',
		display_name='Bunny Fonts',
		categories=[ResourceCategory.FONT],
		priority_tier=0,
		api_available=True,
		self_hostable=True,
		license=_lic(
			spdx_id='OFL-1.1',
			commercial_use=True,
			mcp_download_allowed=True,
			self_hostable=True,
			notes=['GDPR-friendly Google Fonts mirror; same OFL/Apache licenses per family'],
			source_url='https://fonts.bunny.net/faq',
		),
	),
	'fontshare': ResourceProviderMeta(
		provider_id='fontshare',
		display_name='Fontshare',
		categories=[ResourceCategory.FONT],
		priority_tier=0,
		api_available=True,
		self_hostable=True,
		license=_lic(
			spdx_id='Custom',
			commercial_use=True,
			mcp_download_allowed=True,
			self_hostable=True,
			notes=['ITF Free Font License + SIL OFL families; free commercial; no font file resale'],
			source_url='https://www.fontshare.com/licenses/itf-ffl',
		),
	),
	'font-squirrel': ResourceProviderMeta(
		provider_id='font-squirrel',
		display_name='Font Squirrel',
		categories=[ResourceCategory.FONT],
		priority_tier=1,
		self_hostable=True,
		license=_lic(
			spdx_id='Mixed',
			commercial_use=True,
			mcp_download_allowed=True,
			self_hostable=True,
			notes=['Pre-screened “100% free for commercial use” only; adapter must filter to commercial tag'],
			source_url='https://www.fontsquirrel.com/faq',
		),
	),
	'google-fonts': ResourceProviderMeta(
		provider_id='google-fonts',
		display_name='Google Fonts (via Fontsource)',
		categories=[ResourceCategory.FONT],
		priority_tier=0,
		self_hostable=True,
		license=_lic(
			spdx_id='OFL-1.1',
			commercial_use=True,
			mcp_download_allowed=True,
			self_hostable=True,
			notes=['Consume through Fontsource npm — not fonts.googleapis.com CDN in production'],
			source_url='https://fonts.google.com/about',
		),
	),
	# --- Avatars ---
	'dicebear': ResourceProviderMeta(
		provider_id='dicebear',
		display_name='DiceBear (self-host)',
		categories=[ResourceCategory.AVATAR],
		priority_tier=0,
		api_available=True,
		self_hostable=True,
		license=_lic(
			spdx_id='MIT',
			commercial_use=True,
			mcp_download_allowed=True,
			self_hostable=True,
			notes=['Commercial OK when self-hosted; public api.dicebear.com is non-commercial only'],
			source_url='https://www.dicebear.com/how-to-use/http-api/',
		),
		rate_limit_notes='Default adapter uses self-host Docker — not public API',
	),
	'open-peeps': ResourceProviderMeta(
		provider_id='open-peeps',
		display_name='Open Peeps',
		categories=[ResourceCategory.AVATAR, ResourceCategory.ILLUSTRATION],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='CC0', commercial_use=True, mcp_download_allowed=True, source_url='https://www.openpeeps.com/'),
	),
	# --- Illustrations ---
	'open-doodles': ResourceProviderMeta(
		provider_id='open-doodles',
		display_name='Open Doodles',
		categories=[ResourceCategory.ILLUSTRATION],
		priority_tier=0,
		license=_lic(spdx_id='CC0', commercial_use=True, mcp_download_allowed=True, source_url='https://www.opendoodles.com/about'),
	),
	'ira-design': ResourceProviderMeta(
		provider_id='ira-design',
		display_name='IRA Design',
		categories=[ResourceCategory.ILLUSTRATION],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='MIT', commercial_use=True, mcp_download_allowed=True, source_url='https://iradesign.io/'),
	),
	'undraw': ResourceProviderMeta(
		provider_id='undraw',
		display_name='unDraw',
		categories=[ResourceCategory.ILLUSTRATION],
		priority_tier=1,
		license=_lic(
			spdx_id='Custom',
			commercial_use=True,
			attribution_required=False,
			mcp_download_allowed=True,
			api_automation_allowed=False,
			ai_training_allowed=False,
			dataset_use_allowed=False,
			notes=['Commercial OK; automation/AI training prohibited by licensor — manual or licensed access only'],
			source_url='https://undraw.co/license',
		),
	),
	'storyset': ResourceProviderMeta(
		provider_id='storyset',
		display_name='Storyset',
		categories=[ResourceCategory.ILLUSTRATION, ResourceCategory.ANIMATION],
		priority_tier=1,
		license=_lic(
			spdx_id='Custom',
			commercial_use=True,
			attribution_required=True,
			mcp_download_allowed=True,
			api_automation_allowed=False,
			notes=['Commercial OK; free tier requires attribution; scraping/automation prohibited in ToS'],
			source_url='https://storyset.com/terms',
		),
	),
	'svg-repo': ResourceProviderMeta(
		provider_id='svg-repo',
		display_name='SVG Repo',
		categories=[ResourceCategory.SVG, ResourceCategory.GRAPHIC],
		priority_tier=1,
		api_available=True,
		license=_lic(
			spdx_id='Mixed',
			commercial_use=True,
			mcp_download_allowed=True,
			notes=['Commercial assets exist; adapter must skip CC-BY-NC per icon page'],
			source_url='https://www.svgrepo.com/page/licensing',
		),
	),
	# --- Photos ---
	'pexels': ResourceProviderMeta(
		provider_id='pexels',
		display_name='Pexels',
		categories=[ResourceCategory.PHOTO],
		priority_tier=0,
		api_available=True,
		auth_required=True,
		license=_lic(
			spdx_id='Custom',
			commercial_use=True,
			mcp_download_allowed=True,
			api_automation_allowed=True,
			notes=['Pexels License — commercial OK; API requires prominent Pexels link'],
			source_url='https://www.pexels.com/license/',
		),
	),
	'pixabay': ResourceProviderMeta(
		provider_id='pixabay',
		display_name='Pixabay',
		categories=[ResourceCategory.PHOTO],
		priority_tier=1,
		api_available=True,
		auth_required=True,
		license=_lic(
			spdx_id='Custom',
			commercial_use=True,
			mcp_download_allowed=True,
			source_url='https://pixabay.com/service/license/',
		),
	),
	'unsplash': ResourceProviderMeta(
		provider_id='unsplash',
		display_name='Unsplash',
		categories=[ResourceCategory.PHOTO],
		priority_tier=1,
		api_available=True,
		auth_required=True,
		license=_lic(
			spdx_id='Custom',
			commercial_use=True,
			attribution_required=True,
			mcp_download_allowed=True,
			api_automation_allowed=True,
			notes=['Commercial OK; API requires photographer + Unsplash attribution'],
			source_url='https://unsplash.com/api-terms',
		),
	),
	# --- Logos ---
	'simple-icons': ResourceProviderMeta(
		provider_id='simple-icons',
		display_name='Simple Icons',
		categories=[ResourceCategory.LOGO],
		priority_tier=0,
		self_hostable=True,
		license=_lic(
			spdx_id='CC0',
			commercial_use=True,
			mcp_download_allowed=True,
			notes=['SVG CC0; brand trademarks still apply'],
			source_url='https://github.com/simple-icons/simple-icons',
		),
	),
	'thesvg': ResourceProviderMeta(
		provider_id='thesvg',
		display_name='theSVG',
		categories=[ResourceCategory.LOGO, ResourceCategory.SVG],
		priority_tier=0,
		api_available=True,
		license=_lic(
			spdx_id='CC0',
			commercial_use=True,
			mcp_download_allowed=True,
			notes=['Brand logos via curated SVG catalog; trademark rules apply'],
			source_url='https://thesvg.com/',
		),
	),
	# --- Patterns / gradients ---
	'uigradients': ResourceProviderMeta(
		provider_id='uigradients',
		display_name='uiGradients',
		categories=[ResourceCategory.GRADIENT],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='MIT', commercial_use=True, mcp_download_allowed=True, source_url='https://github.com/ghosh/uiGradients'),
	),
	'hero-patterns': ResourceProviderMeta(
		provider_id='hero-patterns',
		display_name='Hero Patterns',
		categories=[ResourceCategory.PATTERN],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='MIT', commercial_use=True, mcp_download_allowed=True, source_url='https://github.com/zcreativelab/react-hero-patterns'),
	),
	# --- 3D ---
	'3dicons': ResourceProviderMeta(
		provider_id='3dicons',
		display_name='3dicons',
		categories=[ResourceCategory.THREE_D],
		priority_tier=1,
		self_hostable=True,
		license=_lic(spdx_id='CC0', commercial_use=True, mcp_download_allowed=True, source_url='https://3dicons.co/'),
	),
	'poly-pizza': ResourceProviderMeta(
		provider_id='poly-pizza',
		display_name='Poly Pizza',
		categories=[ResourceCategory.THREE_D],
		priority_tier=1,
		api_available=True,
		auth_required=True,
		license=_lic(
			spdx_id='Mixed',
			commercial_use=True,
			mcp_download_allowed=True,
			notes=['Per-model CC0 or CC-BY — adapter skips CC-BY when attribution_ok=false'],
			source_url='https://poly.pizza/docs/api/v1.1',
		),
	),
	'poly-haven': ResourceProviderMeta(
		provider_id='poly-haven',
		display_name='Poly Haven',
		categories=[ResourceCategory.THREE_D],
		priority_tier=1,
		api_available=True,
		self_hostable=True,
		license=_lic(
			spdx_id='CC0',
			commercial_use=True,
			mcp_download_allowed=True,
			notes=['Assets CC0 commercial; API ToS restricts commercial API — prefer direct CC0 download'],
			source_url='https://polyhaven.com/license',
		),
	),
	'lottiefiles': ResourceProviderMeta(
		provider_id='lottiefiles',
		display_name='LottieFiles',
		categories=[ResourceCategory.ANIMATION],
		priority_tier=1,
		api_available=True,
		license=_lic(
			spdx_id='Custom',
			commercial_use=True,
			mcp_download_allowed=True,
			notes=['Lottie Simple License — commercial OK; skip community NC animations per asset'],
			source_url='https://lottiefiles.com/page/license',
		),
	),
	'rive': ResourceProviderMeta(
		provider_id='rive',
		display_name='Rive',
		categories=[ResourceCategory.ANIMATION],
		priority_tier=2,
		self_hostable=True,
		license=_lic(
			spdx_id='MIT',
			commercial_use=True,
			mcp_download_allowed=False,
			notes=['Runtime MIT; .riv export requires Rive Editor — metadata/link only in MCP'],
			source_url='https://rive.app/docs/runtimes/getting-started',
		),
	),
}

# Excluded ONLY when commercial use is not allowed (or unverified non-commercial).
EXCLUDED_PROVIDERS: dict[str, ResourceProviderMeta] = {
	'humaaans': ResourceProviderMeta(
		provider_id='humaaans',
		display_name='Humaaans',
		categories=[ResourceCategory.ILLUSTRATION],
		excluded=True,
		exclusion_reason='Commercial license not confirmed — excluded until verified',
		license=_lic(spdx_id='Unknown', commercial_use=False, source_url='https://www.humaaans.com/'),
	),
}

# Merge for lookup; registry filters non-commercial by default.
SEED_PROVIDERS.update(EXCLUDED_PROVIDERS)
