"""3dicons static catalog — CC0 icon slugs from 3dicons.co."""
from __future__ import annotations

# slug format: {hex}-{name} as used on https://3dicons.co/icons/
ICON_CATALOG: list[dict[str, str]] = [
	{'slug': '1acc3d-heart', 'name': 'Heart', 'tags': 'love like favorite'},
	{'slug': '628100-notebook', 'name': 'Notebook', 'tags': 'notes write journal'},
	{'slug': '1858b9-map-pin', 'name': 'Map Pin', 'tags': 'location map marker'},
	{'slug': '0ef25b-calender', 'name': 'Calendar', 'tags': 'date schedule event'},
	{'slug': '8ef1fa-clock', 'name': 'Clock', 'tags': 'time watch'},
	{'slug': '7d956f-wallet', 'name': 'Wallet', 'tags': 'money finance payment'},
	{'slug': '19312f-picture', 'name': 'Picture', 'tags': 'image photo gallery'},
	{'slug': 'ae1a5e-pin', 'name': 'Pin', 'tags': 'pushpin location'},
	{'slug': '49b6f4-target', 'name': 'Target', 'tags': 'goal aim focus'},
	{'slug': '744cc0-rocket', 'name': 'Rocket', 'tags': 'launch startup space'},
	{'slug': '5f20be-computer', 'name': 'Computer', 'tags': 'desktop laptop device'},
	{'slug': '7e47be-setting', 'name': 'Setting', 'tags': 'settings gear config'},
	{'slug': '6bfe8c-fire', 'name': 'Fire', 'tags': 'hot trend flame'},
	{'slug': 'a14880-boy', 'name': 'Boy', 'tags': 'person user avatar'},
	{'slug': '65d841-file-text', 'name': 'File Text', 'tags': 'document file'},
	{'slug': '634add-money', 'name': 'Money', 'tags': 'cash finance dollar'},
	{'slug': '8bbd16-location', 'name': 'Location', 'tags': 'gps map place'},
	{'slug': 'b91186-shield', 'name': 'Shield', 'tags': 'security protect safe'},
	{'slug': '1fded0-mobile', 'name': 'Mobile', 'tags': 'phone smartphone device'},
	{'slug': '176980-folder', 'name': 'Folder', 'tags': 'directory files storage'},
	{'slug': '39121b-medal', 'name': 'Medal', 'tags': 'award achievement badge'},
	{'slug': '66b0f8-pencil', 'name': 'Pencil', 'tags': 'edit write draw'},
	{'slug': 'b81ead-headphone', 'name': 'Headphone', 'tags': 'audio music listen'},
	{'slug': 'b7c633-folder-fav', 'name': 'Folder Favorite', 'tags': 'star bookmark'},
	{'slug': 'fa6099-travel', 'name': 'Travel', 'tags': 'trip vacation luggage'},
	{'slug': '56180e-lab', 'name': 'Lab', 'tags': 'science experiment'},
	{'slug': '7bbb2b-file-new', 'name': 'File New', 'tags': 'create document add'},
	{'slug': '879a83-rupee', 'name': 'Rupee', 'tags': 'currency money'},
	{'slug': 'e216db-candy', 'name': 'Candy', 'tags': 'sweet snack'},
	{'slug': '313578-megaphone', 'name': 'Megaphone', 'tags': 'announce marketing loud'},
	{'slug': '1b714e-tick', 'name': 'Tick', 'tags': 'check success done'},
	{'slug': '269bcd-gift-box', 'name': 'Gift Box', 'tags': 'present reward'},
	{'slug': 'a0f7a1-at', 'name': 'At', 'tags': 'email mention contact'},
	{'slug': 'b4a0af-zoom', 'name': 'Zoom', 'tags': 'search magnify'},
	{'slug': '8924a0-mail', 'name': 'Mail', 'tags': 'email message inbox'},
	{'slug': '4a4275-chart', 'name': 'Chart', 'tags': 'analytics graph data'},
	{'slug': '4e7918-thumb-up', 'name': 'Thumb Up', 'tags': 'like approve positive'},
	{'slug': 'f0f795-chat-text', 'name': 'Chat Text', 'tags': 'message conversation'},
	{'slug': 'd3d0c0-hash', 'name': 'Hash', 'tags': 'tag hashtag'},
	{'slug': '135b8b-bulb', 'name': 'Bulb', 'tags': 'idea light innovation'},
	{'slug': '31b611-instagram', 'name': 'Instagram', 'tags': 'social media'},
	{'slug': '5cab4b-youtube', 'name': 'Youtube', 'tags': 'social video'},
	{'slug': '421bcd-credit-card', 'name': 'Credit Card', 'tags': 'payment checkout'},
	{'slug': 'a811da-cloud', 'name': 'Cloud', 'tags': 'storage weather saas'},
	{'slug': 'c84e89-star', 'name': 'Star', 'tags': 'favorite rating'},
	{'slug': 'f15f79-lock', 'name': 'Lock', 'tags': 'security password private'},
	{'slug': '72c6ef-unlock', 'name': 'Unlock', 'tags': 'open access'},
	{'slug': '00a651-home', 'name': 'Home', 'tags': 'house dashboard'},
	{'slug': '004e8f-search', 'name': 'Search', 'tags': 'find magnify'},
]
